// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  Artifact,
  ArtifactFull,
  ArtifactFullRow,
  ArtifactPayload,
  ArtifactPiece,
  ArtifactPiecePayload,
} from '../models';
import { Expanded } from '../types';

/**
 * Artifact sets and the pieces in them.
 */
@Injectable({ providedIn: 'root' })
export class ArtifactApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/artifacts`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createArtifact(body: ArtifactPayload): Observable<Expanded<Artifact, 'created_by'>> {
    return this._http.post<Expanded<Artifact, 'created_by'>>('/api/artifacts', body);
  }

  /**
   * `POST /api/artifacts/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createArtifactFull(body: FormData): Observable<Artifact> {
    return this._http.post<Artifact>('/api/artifacts/full', body);
  }

  /**
   * `POST /api/artifacts-pieces`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createArtifactPiece(body: ArtifactPiecePayload): Observable<Expanded<ArtifactPiece, 'created_by'>> {
    return this._http.post<Expanded<ArtifactPiece, 'created_by'>>('/api/artifacts-pieces', body);
  }

  /**
   * `DELETE /api/artifacts/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteArtifact(id: number): Observable<Artifact> {
    return this._http.delete<Artifact>(`/api/artifacts/${id}`);
  }

  /**
   * `DELETE /api/artifacts-pieces/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteArtifactPiece(id: number): Observable<ArtifactPiece> {
    return this._http.delete<ArtifactPiece>(`/api/artifacts-pieces/${id}`);
  }

  /**
   * `GET /api/artifacts/{id}`
   */
  getArtifact(id: number): Observable<Expanded<Artifact, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<Artifact, 'created_by' | 'updated_by'>>(`/api/artifacts/${id}`);
  }

  /**
   * `GET /api/artifacts/{id}/full`
   */
  getArtifactFull(id: number): Observable<ArtifactFull> {
    return this._http.get<ArtifactFull>(`/api/artifacts/${id}/full`);
  }

  /**
   * `GET /api/artifacts-pieces/{id}`
   */
  getArtifactPiece(id: number): Observable<Expanded<ArtifactPiece, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<ArtifactPiece, 'created_by' | 'updated_by'>>(`/api/artifacts-pieces/${id}`);
  }

  /**
   * `GET /api/artifacts-pieces`
   */
  getArtifactPieces(): Observable<Expanded<ArtifactPiece, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<ArtifactPiece, 'created_by' | 'updated_by'>[]>('/api/artifacts-pieces');
  }

  /**
   * `GET /api/artifacts`
   */
  getArtifacts(): Observable<Expanded<Artifact, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<Artifact, 'created_by' | 'updated_by'>[]>('/api/artifacts');
  }

  /**
   * `GET /api/artifacts/full`
   */
  getArtifactsFull(): Observable<ArtifactFullRow[]> {
    return this._http.get<ArtifactFullRow[]>('/api/artifacts/full');
  }

  /**
   * `PUT /api/artifacts/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateArtifact(id: number, body: Partial<ArtifactPayload>): Observable<Expanded<Artifact, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<Artifact, 'created_by' | 'updated_by'>>(`/api/artifacts/${id}`, body);
  }

  /**
   * `PUT /api/artifacts/{id}/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateArtifactFull(id: number, body: FormData): Observable<Artifact> {
    return this._http.put<Artifact>(`/api/artifacts/${id}/full`, body);
  }

  /**
   * `PUT /api/artifacts-pieces/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateArtifactPiece(id: number, body: Partial<ArtifactPiecePayload>): Observable<Expanded<ArtifactPiece, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<ArtifactPiece, 'created_by' | 'updated_by'>>(`/api/artifacts-pieces/${id}`, body);
  }
}
