// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { AuditLogFilters, AuditLogPage, AuditLogQuery } from '../types';
import { toHttpParams } from '../http-params';

/**
 * Who changed which row, and to what.
 */
@Injectable({ providedIn: 'root' })
export class AuditLogApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `GET /api/audit-logs/filters`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getAuditLogFilters(): Observable<AuditLogFilters> {
    return this._http.get<AuditLogFilters>('/api/audit-logs/filters');
  }

  /**
   * `GET /api/audit-logs`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getAuditLogPage(params: AuditLogQuery): Observable<AuditLogPage> {
    return this._http.get<AuditLogPage>('/api/audit-logs', { params: toHttpParams(params) });
  }
}
