// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  ApiMessage,
  AuthSession,
  AuthUser,
  ChangePasswordRequest,
  LanguageChanged,
  LanguageRequest,
  LoginRequest,
  RegisterRequest,
  ThemeChanged,
  ThemeRequest,
} from '../types';

/**
 * Registering, signing in, and the settings that hang off the signed-in account.
 */
@Injectable({ providedIn: 'root' })
export class AuthApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `GET /api/auth/me`
   *
   * Requires a signed-in user.
   */
  getCurrentUser(): Observable<AuthUser> {
    return this._http.get<AuthUser>('/api/auth/me');
  }

  /**
   * `PUT /api/auth/password`
   *
   * Requires a signed-in user.
   */
  changePassword(body: ChangePasswordRequest): Observable<ApiMessage> {
    return this._http.put<ApiMessage>('/api/auth/password', body);
  }

  /**
   * `POST /api/auth/login`
   */
  login(body: LoginRequest): Observable<AuthSession> {
    return this._http.post<AuthSession>('/api/auth/login', body);
  }

  /**
   * `POST /api/auth/logout`
   */
  logout(body: Record<string, unknown>): Observable<ApiMessage> {
    return this._http.post<ApiMessage>('/api/auth/logout', body);
  }

  /**
   * `POST /api/auth/register`
   */
  register(body: RegisterRequest): Observable<AuthSession> {
    return this._http.post<AuthSession>('/api/auth/register', body);
  }

  /**
   * `PUT /api/auth/language`
   *
   * Requires a signed-in user.
   */
  setLanguage(body: LanguageRequest): Observable<LanguageChanged> {
    return this._http.put<LanguageChanged>('/api/auth/language', body);
  }

  /**
   * `PUT /api/auth/theme`
   *
   * Requires a signed-in user.
   */
  setTheme(body: ThemeRequest): Observable<ThemeChanged> {
    return this._http.put<ThemeChanged>('/api/auth/theme', body);
  }
}
