// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  ApiMessage,
  AuthMailRequested,
  AuthPending,
  AuthProviders,
  AuthSession,
  AuthUser,
  LanguageChanged,
  SessionList,
  SessionsEnded,
  ThemeChanged,
  TotpRecoveryCodes,
  TotpSetup,
} from '../models';
import {
  ChangePasswordRequest,
  ConfirmEmailRequest,
  EmailRequest,
  EnabledRequest,
  GoogleCredentialRequest,
  LanguageRequest,
  LoginCodeRequest,
  LoginRequest,
  PasswordResetRequest,
  RegisterRequest,
  SetOwnPasswordRequest,
  ThemeRequest,
  TotpCodeRequest,
} from '../types';

/**
 * Registering, signing in, and the settings that hang off the signed-in account.
 */
@Injectable({ providedIn: 'root' })
export class AuthApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/auth/confirm`
   */
  confirmEmail(body: ConfirmEmailRequest): Observable<AuthSession> {
    return this._http.post<AuthSession>('/api/auth/confirm', body);
  }

  /**
   * `POST /api/auth/google/link`
   *
   * Requires a signed-in user.
   */
  connectGoogle(body: GoogleCredentialRequest): Observable<AuthUser> {
    return this._http.post<AuthUser>('/api/auth/google/link', body);
  }

  /**
   * `POST /api/auth/2fa/disable`
   *
   * Requires a signed-in user.
   */
  disableTwoFactor(body: TotpCodeRequest): Observable<AuthUser> {
    return this._http.post<AuthUser>('/api/auth/2fa/disable', body);
  }

  /**
   * `DELETE /api/auth/google/link`
   *
   * Requires a signed-in user.
   */
  disconnectGoogle(): Observable<AuthUser> {
    return this._http.delete<AuthUser>('/api/auth/google/link');
  }

  /**
   * `POST /api/auth/2fa/enable`
   *
   * Requires a signed-in user.
   */
  enableTwoFactor(body: TotpCodeRequest): Observable<TotpRecoveryCodes> {
    return this._http.post<TotpRecoveryCodes>('/api/auth/2fa/enable', body);
  }

  /**
   * `DELETE /api/auth/sessions`
   *
   * Requires a signed-in user.
   */
  endOtherSessions(): Observable<SessionsEnded> {
    return this._http.delete<SessionsEnded>('/api/auth/sessions');
  }

  /**
   * `DELETE /api/auth/sessions/{id}`
   *
   * Requires a signed-in user.
   */
  endSession(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/auth/sessions/${id}`);
  }

  /**
   * `GET /api/auth/providers`
   */
  getAuthProviders(): Observable<AuthProviders> {
    return this._http.get<AuthProviders>('/api/auth/providers');
  }

  /**
   * `GET /api/auth/me`
   *
   * Requires a signed-in user.
   */
  getCurrentUser(): Observable<AuthUser> {
    return this._http.get<AuthUser>('/api/auth/me');
  }

  /**
   * `GET /api/auth/sessions`
   *
   * Requires a signed-in user.
   */
  getSessions(): Observable<SessionList> {
    return this._http.get<SessionList>('/api/auth/sessions');
  }

  /**
   * `PUT /api/auth/password`
   *
   * Requires a signed-in user.
   */
  changePassword(body: ChangePasswordRequest): Observable<ApiMessage> {
    return this._http.put<ApiMessage>('/api/auth/password', body);
  }

  /**
   * `POST /api/auth/login`
   */
  login(body: LoginRequest): Observable<AuthSession> {
    return this._http.post<AuthSession>('/api/auth/login', body);
  }

  /**
   * `POST /api/auth/logout`
   */
  logout(body: Record<string, unknown>): Observable<ApiMessage> {
    return this._http.post<ApiMessage>('/api/auth/logout', body);
  }

  /**
   * `POST /api/auth/2fa/recovery`
   *
   * Requires a signed-in user.
   */
  regenerateRecoveryCodes(body: TotpCodeRequest): Observable<TotpRecoveryCodes> {
    return this._http.post<TotpRecoveryCodes>('/api/auth/2fa/recovery', body);
  }

  /**
   * `POST /api/auth/register`
   */
  register(body: RegisterRequest): Observable<AuthPending> {
    return this._http.post<AuthPending>('/api/auth/register', body);
  }

  /**
   * `POST /api/auth/login/code`
   */
  requestLoginCode(body: EmailRequest): Observable<AuthMailRequested> {
    return this._http.post<AuthMailRequested>('/api/auth/login/code', body);
  }

  /**
   * `POST /api/auth/password/forgot`
   */
  requestPasswordReset(body: EmailRequest): Observable<AuthMailRequested> {
    return this._http.post<AuthMailRequested>('/api/auth/password/forgot', body);
  }

  /**
   * `POST /api/auth/confirm/resend`
   */
  resendConfirmation(body: EmailRequest): Observable<AuthMailRequested> {
    return this._http.post<AuthMailRequested>('/api/auth/confirm/resend', body);
  }

  /**
   * `POST /api/auth/password/reset`
   */
  resetPassword(body: PasswordResetRequest): Observable<AuthSession> {
    return this._http.post<AuthSession>('/api/auth/password/reset', body);
  }

  /**
   * `PUT /api/auth/language`
   *
   * Requires a signed-in user.
   */
  setLanguage(body: LanguageRequest): Observable<LanguageChanged> {
    return this._http.put<LanguageChanged>('/api/auth/language', body);
  }

  /**
   * `POST /api/auth/password/set`
   *
   * Requires a signed-in user.
   */
  setOwnPassword(body: SetOwnPasswordRequest): Observable<AuthUser> {
    return this._http.post<AuthUser>('/api/auth/password/set', body);
  }

  /**
   * `PUT /api/auth/password/enabled`
   *
   * Requires a signed-in user.
   */
  setPasswordLoginEnabled(body: EnabledRequest): Observable<AuthUser> {
    return this._http.put<AuthUser>('/api/auth/password/enabled', body);
  }

  /**
   * `PUT /api/auth/theme`
   *
   * Requires a signed-in user.
   */
  setTheme(body: ThemeRequest): Observable<ThemeChanged> {
    return this._http.put<ThemeChanged>('/api/auth/theme', body);
  }

  /**
   * `POST /api/auth/login/code/verify`
   */
  signInWithCode(body: LoginCodeRequest): Observable<AuthSession> {
    return this._http.post<AuthSession>('/api/auth/login/code/verify', body);
  }

  /**
   * `POST /api/auth/google`
   */
  signInWithGoogle(body: GoogleCredentialRequest): Observable<AuthSession> {
    return this._http.post<AuthSession>('/api/auth/google', body);
  }

  /**
   * `POST /api/auth/2fa/setup`
   *
   * Requires a signed-in user.
   */
  startTwoFactorSetup(body: Record<string, unknown>): Observable<TotpSetup> {
    return this._http.post<TotpSetup>('/api/auth/2fa/setup', body);
  }
}
