// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Background, BackgroundPayload } from '../models';
import { ApiMessage } from '../types';

/**
 * Site backgrounds a visitor can pick between.
 */
@Injectable({ providedIn: 'root' })
export class BackgroundApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/backgrounds`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createBackground(body: BackgroundPayload): Observable<Background> {
    return this._http.post<Background>('/api/backgrounds', body);
  }

  /**
   * `DELETE /api/backgrounds/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteBackground(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/backgrounds/${id}`);
  }

  /**
   * `GET /api/backgrounds/{id}`
   */
  getBackground(id: number): Observable<Background> {
    return this._http.get<Background>(`/api/backgrounds/${id}`);
  }

  /**
   * `GET /api/backgrounds`
   */
  getBackgrounds(): Observable<Background[]> {
    return this._http.get<Background[]>('/api/backgrounds');
  }

  /**
   * `PUT /api/backgrounds/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateBackground(id: number, body: Partial<BackgroundPayload>): Observable<Background> {
    return this._http.put<Background>(`/api/backgrounds/${id}`, body);
  }
}
