// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  ApiMessage,
  BackupEntry,
  BackupPreview,
  BackupRequest,
  BackupStatus,
  RestoreRequest,
  RestoreResult,
} from '../types';

/**
 * Database dumps: listing them, making them, and restoring one.
 */
@Injectable({ providedIn: 'root' })
export class BackupApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/backups`
   *
   * Requires the `ADMIN` role.
   */
  createBackup(body: BackupRequest): Observable<BackupEntry> {
    return this._http.post<BackupEntry>('/api/backups', body);
  }

  /**
   * `DELETE /api/backups/{id}`
   *
   * Requires the `ADMIN` role.
   */
  deleteBackup(id: string): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/backups/${encodeURIComponent(id)}`);
  }

  /**
   * `GET /api/backups/{id}/download/{alias}`
   *
   * Requires the `ADMIN` role.
   */
  downloadBackup(id: string, alias: string): Observable<Blob> {
    return this._http.get<Blob>(`/api/backups/${encodeURIComponent(id)}/download/${encodeURIComponent(alias)}`, { responseType: 'blob' as 'json' });
  }

  /**
   * `GET /api/backups/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getBackup(id: string): Observable<BackupEntry> {
    return this._http.get<BackupEntry>(`/api/backups/${encodeURIComponent(id)}`);
  }

  /**
   * `GET /api/backups`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getBackups(): Observable<BackupEntry[]> {
    return this._http.get<BackupEntry[]>('/api/backups');
  }

  /**
   * `GET /api/backups/status`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getBackupStatus(): Observable<BackupStatus> {
    return this._http.get<BackupStatus>('/api/backups/status');
  }

  /**
   * `GET /api/backups/{id}/preview/{alias}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  previewBackup(id: string, alias: string): Observable<BackupPreview> {
    return this._http.get<BackupPreview>(`/api/backups/${encodeURIComponent(id)}/preview/${encodeURIComponent(alias)}`);
  }

  /**
   * `POST /api/backups/{id}/restore/{alias}`
   *
   * Requires the `ADMIN` role.
   */
  restoreBackup(id: string, alias: string, body: RestoreRequest): Observable<RestoreResult> {
    return this._http.post<RestoreResult>(`/api/backups/${encodeURIComponent(id)}/restore/${encodeURIComponent(alias)}`, body);
  }
}
