// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  Banner,
  BannerCharacter,
  BannerCharacterPayload,
  BannerPayload,
  BannerWeapon,
  BannerWeaponPayload,
} from '../models';
import { ApiMessage, BannerFull, Expanded } from '../types';

/**
 * Wish banners and the characters and weapons on them.
 */
@Injectable({ providedIn: 'root' })
export class BannerApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/banners`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createBanner(body: BannerPayload): Observable<Expanded<Banner, 'created_by'>> {
    return this._http.post<Expanded<Banner, 'created_by'>>('/api/banners', body);
  }

  /**
   * `POST /api/banners/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createBannerFull(body: FormData): Observable<Banner> {
    return this._http.post<Banner>('/api/banners/full', body);
  }

  /**
   * `POST /api/banners-characters`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createBannerCharacter(body: BannerCharacterPayload): Observable<Expanded<BannerCharacter, 'created_by'>> {
    return this._http.post<Expanded<BannerCharacter, 'created_by'>>('/api/banners-characters', body);
  }

  /**
   * `POST /api/banners-weapons`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createBannerWeapon(body: BannerWeaponPayload): Observable<Expanded<BannerWeapon, 'created_by'>> {
    return this._http.post<Expanded<BannerWeapon, 'created_by'>>('/api/banners-weapons', body);
  }

  /**
   * `DELETE /api/banners/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteBanner(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/banners/${id}`);
  }

  /**
   * `DELETE /api/banners-characters/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteBannerCharacter(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/banners-characters/${id}`);
  }

  /**
   * `DELETE /api/banners-weapons/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteBannerWeapon(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/banners-weapons/${id}`);
  }

  /**
   * `GET /api/banners/{id}`
   */
  getBanner(id: number): Observable<Expanded<Banner, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<Banner, 'created_by' | 'updated_by'>>(`/api/banners/${id}`);
  }

  /**
   * `GET /api/banners/{id}/full`
   */
  getBannerFull(id: number): Observable<BannerFull> {
    return this._http.get<BannerFull>(`/api/banners/${id}/full`);
  }

  /**
   * `GET /api/banners-characters/{id}`
   */
  getBannerCharacter(id: number): Observable<Expanded<BannerCharacter, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<BannerCharacter, 'created_by' | 'updated_by'>>(`/api/banners-characters/${id}`);
  }

  /**
   * `GET /api/banners-characters`
   */
  getBannerCharacters(): Observable<Expanded<BannerCharacter, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<BannerCharacter, 'created_by' | 'updated_by'>[]>('/api/banners-characters');
  }

  /**
   * `GET /api/banners`
   */
  getBanners(): Observable<Expanded<Banner, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<Banner, 'created_by' | 'updated_by'>[]>('/api/banners');
  }

  /**
   * `GET /api/banners/full`
   */
  getBannersFull(): Observable<BannerFull[]> {
    return this._http.get<BannerFull[]>('/api/banners/full');
  }

  /**
   * `GET /api/banners-weapons/{id}`
   */
  getBannerWeapon(id: number): Observable<Expanded<BannerWeapon, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<BannerWeapon, 'created_by' | 'updated_by'>>(`/api/banners-weapons/${id}`);
  }

  /**
   * `GET /api/banners-weapons`
   */
  getBannerWeapons(): Observable<Expanded<BannerWeapon, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<BannerWeapon, 'created_by' | 'updated_by'>[]>('/api/banners-weapons');
  }

  /**
   * `PUT /api/banners/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateBanner(id: number, body: Partial<BannerPayload>): Observable<Expanded<Banner, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<Banner, 'created_by' | 'updated_by'>>(`/api/banners/${id}`, body);
  }

  /**
   * `PUT /api/banners/{id}/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateBannerFull(id: number, body: FormData): Observable<Banner> {
    return this._http.put<Banner>(`/api/banners/${id}/full`, body);
  }

  /**
   * `PUT /api/banners-characters/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateBannerCharacter(id: number, body: Partial<BannerCharacterPayload>): Observable<Expanded<BannerCharacter, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<BannerCharacter, 'created_by' | 'updated_by'>>(`/api/banners-characters/${id}`, body);
  }

  /**
   * `PUT /api/banners-weapons/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateBannerWeapon(id: number, body: Partial<BannerWeaponPayload>): Observable<Expanded<BannerWeapon, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<BannerWeapon, 'created_by' | 'updated_by'>>(`/api/banners-weapons/${id}`, body);
  }
}
