// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  Character,
  CharacterAscension,
  CharacterAscensionCost,
  CharacterAscensionCostPayload,
  CharacterAscensionPayload,
  CharacterBuild,
  CharacterBuildArtifact,
  CharacterBuildArtifactPayload,
  CharacterBuildMainStat,
  CharacterBuildMainStatPayload,
  CharacterBuildPayload,
  CharacterBuildRecommendedStat,
  CharacterBuildRecommendedStatPayload,
  CharacterBuildSubStat,
  CharacterBuildSubStatPayload,
  CharacterBuildTalent,
  CharacterBuildTalentPayload,
  CharacterBuildTeam,
  CharacterBuildTeamCharacter,
  CharacterBuildTeamCharacterPayload,
  CharacterBuildTeamPayload,
  CharacterBuildWeapon,
  CharacterBuildWeaponPayload,
  CharacterConstellation,
  CharacterConstellationPayload,
  CharacterPayload,
  CharacterRelationship,
  CharacterRelationshipPayload,
  CharacterRole,
  CharacterRolePayload,
  CharacterTalent,
  CharacterTalentCost,
  CharacterTalentCostPayload,
  CharacterTalentPayload,
  CharacterVoiceOver,
  CharacterVoiceOverPayload,
} from '../models';
import { ApiMessage, CharacterFull, Expanded } from '../types';

/**
 * Characters and everything hanging off one - talents, ascensions, constellations, builds.
 */
@Injectable({ providedIn: 'root' })
export class CharacterApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/characters`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacter(body: CharacterPayload): Observable<Expanded<Character, 'created_by'>> {
    return this._http.post<Expanded<Character, 'created_by'>>('/api/characters', body);
  }

  /**
   * `POST /api/characters-ascensions`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterAscension(body: CharacterAscensionPayload): Observable<Expanded<CharacterAscension, 'created_by'>> {
    return this._http.post<Expanded<CharacterAscension, 'created_by'>>('/api/characters-ascensions', body);
  }

  /**
   * `POST /api/characters-ascensions-cost`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterAscensionCost(body: CharacterAscensionCostPayload): Observable<Expanded<CharacterAscensionCost, 'created_by'>> {
    return this._http.post<Expanded<CharacterAscensionCost, 'created_by'>>('/api/characters-ascensions-cost', body);
  }

  /**
   * `POST /api/characters-builds`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterBuild(body: CharacterBuildPayload): Observable<Expanded<CharacterBuild, 'created_by'>> {
    return this._http.post<Expanded<CharacterBuild, 'created_by'>>('/api/characters-builds', body);
  }

  /**
   * `POST /api/characters-builds-artifacts`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterBuildArtifact(body: CharacterBuildArtifactPayload): Observable<Expanded<CharacterBuildArtifact, 'created_by'>> {
    return this._http.post<Expanded<CharacterBuildArtifact, 'created_by'>>('/api/characters-builds-artifacts', body);
  }

  /**
   * `POST /api/characters-builds-main-stats`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterBuildMainStat(body: CharacterBuildMainStatPayload): Observable<Expanded<CharacterBuildMainStat, 'created_by'>> {
    return this._http.post<Expanded<CharacterBuildMainStat, 'created_by'>>('/api/characters-builds-main-stats', body);
  }

  /**
   * `POST /api/characters-builds-recommended-stats`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterBuildRecommendedStat(body: CharacterBuildRecommendedStatPayload): Observable<Expanded<CharacterBuildRecommendedStat, 'created_by'>> {
    return this._http.post<Expanded<CharacterBuildRecommendedStat, 'created_by'>>('/api/characters-builds-recommended-stats', body);
  }

  /**
   * `POST /api/characters-builds-sub-stats`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterBuildSubStat(body: CharacterBuildSubStatPayload): Observable<Expanded<CharacterBuildSubStat, 'created_by'>> {
    return this._http.post<Expanded<CharacterBuildSubStat, 'created_by'>>('/api/characters-builds-sub-stats', body);
  }

  /**
   * `POST /api/characters-builds-talents`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterBuildTalent(body: CharacterBuildTalentPayload): Observable<Expanded<CharacterBuildTalent, 'created_by'>> {
    return this._http.post<Expanded<CharacterBuildTalent, 'created_by'>>('/api/characters-builds-talents', body);
  }

  /**
   * `POST /api/characters-builds-teams`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterBuildTeam(body: CharacterBuildTeamPayload): Observable<Expanded<CharacterBuildTeam, 'created_by'>> {
    return this._http.post<Expanded<CharacterBuildTeam, 'created_by'>>('/api/characters-builds-teams', body);
  }

  /**
   * `POST /api/characters-builds-teams-characters`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterBuildTeamCharacter(body: CharacterBuildTeamCharacterPayload): Observable<Expanded<CharacterBuildTeamCharacter, 'created_by'>> {
    return this._http.post<Expanded<CharacterBuildTeamCharacter, 'created_by'>>('/api/characters-builds-teams-characters', body);
  }

  /**
   * `POST /api/characters-builds-weapons`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterBuildWeapon(body: CharacterBuildWeaponPayload): Observable<Expanded<CharacterBuildWeapon, 'created_by'>> {
    return this._http.post<Expanded<CharacterBuildWeapon, 'created_by'>>('/api/characters-builds-weapons', body);
  }

  /**
   * `POST /api/characters-constellations`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterConstellation(body: CharacterConstellationPayload): Observable<Expanded<CharacterConstellation, 'created_by'>> {
    return this._http.post<Expanded<CharacterConstellation, 'created_by'>>('/api/characters-constellations', body);
  }

  /**
   * `POST /api/characters/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterFull(body: FormData): Observable<Expanded<Character, 'created_by'>> {
    return this._http.post<Expanded<Character, 'created_by'>>('/api/characters/full', body);
  }

  /**
   * `POST /api/characters-relationships`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterRelationship(body: CharacterRelationshipPayload): Observable<Expanded<CharacterRelationship, 'created_by'>> {
    return this._http.post<Expanded<CharacterRelationship, 'created_by'>>('/api/characters-relationships', body);
  }

  /**
   * `POST /api/characters-roles`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterRole(body: CharacterRolePayload): Observable<Expanded<CharacterRole, 'created_by'>> {
    return this._http.post<Expanded<CharacterRole, 'created_by'>>('/api/characters-roles', body);
  }

  /**
   * `POST /api/characters-talents`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterTalent(body: CharacterTalentPayload): Observable<Expanded<CharacterTalent, 'created_by'>> {
    return this._http.post<Expanded<CharacterTalent, 'created_by'>>('/api/characters-talents', body);
  }

  /**
   * `POST /api/characters-talents-cost`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterTalentCost(body: CharacterTalentCostPayload): Observable<Expanded<CharacterTalentCost, 'created_by'>> {
    return this._http.post<Expanded<CharacterTalentCost, 'created_by'>>('/api/characters-talents-cost', body);
  }

  /**
   * `POST /api/characters-voice-overs`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createCharacterVoiceOver(body: CharacterVoiceOverPayload): Observable<Expanded<CharacterVoiceOver, 'created_by'>> {
    return this._http.post<Expanded<CharacterVoiceOver, 'created_by'>>('/api/characters-voice-overs', body);
  }

  /**
   * `DELETE /api/characters/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacter(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters/${id}`);
  }

  /**
   * `DELETE /api/characters-ascensions/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterAscension(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-ascensions/${id}`);
  }

  /**
   * `DELETE /api/characters-ascensions-cost/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterAscensionCost(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-ascensions-cost/${id}`);
  }

  /**
   * `DELETE /api/characters-builds/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterBuild(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-builds/${id}`);
  }

  /**
   * `DELETE /api/characters-builds-artifacts/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterBuildArtifact(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-builds-artifacts/${id}`);
  }

  /**
   * `DELETE /api/characters-builds-main-stats/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterBuildMainStat(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-builds-main-stats/${id}`);
  }

  /**
   * `DELETE /api/characters-builds-recommended-stats/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterBuildRecommendedStat(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-builds-recommended-stats/${id}`);
  }

  /**
   * `DELETE /api/characters-builds-sub-stats/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterBuildSubStat(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-builds-sub-stats/${id}`);
  }

  /**
   * `DELETE /api/characters-builds-talents/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterBuildTalent(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-builds-talents/${id}`);
  }

  /**
   * `DELETE /api/characters-builds-teams/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterBuildTeam(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-builds-teams/${id}`);
  }

  /**
   * `DELETE /api/characters-builds-teams-characters/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterBuildTeamCharacter(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-builds-teams-characters/${id}`);
  }

  /**
   * `DELETE /api/characters-builds-weapons/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterBuildWeapon(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-builds-weapons/${id}`);
  }

  /**
   * `DELETE /api/characters-constellations/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterConstellation(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-constellations/${id}`);
  }

  /**
   * `DELETE /api/characters-relationships/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterRelationship(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-relationships/${id}`);
  }

  /**
   * `DELETE /api/characters-roles/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterRole(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-roles/${id}`);
  }

  /**
   * `DELETE /api/characters-talents/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterTalent(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-talents/${id}`);
  }

  /**
   * `DELETE /api/characters-talents-cost/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterTalentCost(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-talents-cost/${id}`);
  }

  /**
   * `DELETE /api/characters-voice-overs/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteCharacterVoiceOver(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/characters-voice-overs/${id}`);
  }

  /**
   * `GET /api/characters/{id}`
   */
  getCharacter(id: number): Observable<Expanded<Character, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<Character, 'created_by' | 'updated_by'>>(`/api/characters/${id}`);
  }

  /**
   * `GET /api/characters-ascensions/{id}`
   */
  getCharacterAscension(id: number): Observable<Expanded<CharacterAscension, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterAscension, 'created_by' | 'updated_by'>>(`/api/characters-ascensions/${id}`);
  }

  /**
   * `GET /api/characters-ascensions-cost/{id}`
   */
  getCharacterAscensionCost(id: number): Observable<Expanded<CharacterAscensionCost, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterAscensionCost, 'created_by' | 'updated_by'>>(`/api/characters-ascensions-cost/${id}`);
  }

  /**
   * `GET /api/characters-ascensions-cost`
   */
  getCharacterAscensionCosts(): Observable<Expanded<CharacterAscensionCost, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterAscensionCost, 'created_by' | 'updated_by'>[]>('/api/characters-ascensions-cost');
  }

  /**
   * `GET /api/characters-ascensions`
   */
  getCharacterAscensions(): Observable<Expanded<CharacterAscension, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterAscension, 'created_by' | 'updated_by'>[]>('/api/characters-ascensions');
  }

  /**
   * `GET /api/characters-builds/{id}`
   */
  getCharacterBuild(id: number): Observable<Expanded<CharacterBuild, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterBuild, 'created_by' | 'updated_by'>>(`/api/characters-builds/${id}`);
  }

  /**
   * `GET /api/characters-builds-artifacts/{id}`
   */
  getCharacterBuildArtifact(id: number): Observable<Expanded<CharacterBuildArtifact, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterBuildArtifact, 'created_by' | 'updated_by'>>(`/api/characters-builds-artifacts/${id}`);
  }

  /**
   * `GET /api/characters-builds-artifacts`
   */
  getCharacterBuildArtifacts(): Observable<Expanded<CharacterBuildArtifact, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterBuildArtifact, 'created_by' | 'updated_by'>[]>('/api/characters-builds-artifacts');
  }

  /**
   * `GET /api/characters-builds-main-stats/{id}`
   */
  getCharacterBuildMainStat(id: number): Observable<Expanded<CharacterBuildMainStat, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterBuildMainStat, 'created_by' | 'updated_by'>>(`/api/characters-builds-main-stats/${id}`);
  }

  /**
   * `GET /api/characters-builds-main-stats`
   */
  getCharacterBuildMainStats(): Observable<Expanded<CharacterBuildMainStat, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterBuildMainStat, 'created_by' | 'updated_by'>[]>('/api/characters-builds-main-stats');
  }

  /**
   * `GET /api/characters-builds-recommended-stats/{id}`
   */
  getCharacterBuildRecommendedStat(id: number): Observable<Expanded<CharacterBuildRecommendedStat, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterBuildRecommendedStat, 'created_by' | 'updated_by'>>(`/api/characters-builds-recommended-stats/${id}`);
  }

  /**
   * `GET /api/characters-builds-recommended-stats`
   */
  getCharacterBuildRecommendedStats(): Observable<Expanded<CharacterBuildRecommendedStat, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterBuildRecommendedStat, 'created_by' | 'updated_by'>[]>('/api/characters-builds-recommended-stats');
  }

  /**
   * `GET /api/characters-builds`
   */
  getCharacterBuilds(): Observable<Expanded<CharacterBuild, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterBuild, 'created_by' | 'updated_by'>[]>('/api/characters-builds');
  }

  /**
   * `GET /api/characters-builds-sub-stats/{id}`
   */
  getCharacterBuildSubStat(id: number): Observable<Expanded<CharacterBuildSubStat, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterBuildSubStat, 'created_by' | 'updated_by'>>(`/api/characters-builds-sub-stats/${id}`);
  }

  /**
   * `GET /api/characters-builds-sub-stats`
   */
  getCharacterBuildSubStats(): Observable<Expanded<CharacterBuildSubStat, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterBuildSubStat, 'created_by' | 'updated_by'>[]>('/api/characters-builds-sub-stats');
  }

  /**
   * `GET /api/characters-builds-talents/{id}`
   */
  getCharacterBuildTalent(id: number): Observable<Expanded<CharacterBuildTalent, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterBuildTalent, 'created_by' | 'updated_by'>>(`/api/characters-builds-talents/${id}`);
  }

  /**
   * `GET /api/characters-builds-talents`
   */
  getCharacterBuildTalents(): Observable<Expanded<CharacterBuildTalent, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterBuildTalent, 'created_by' | 'updated_by'>[]>('/api/characters-builds-talents');
  }

  /**
   * `GET /api/characters-builds-teams/{id}`
   */
  getCharacterBuildTeam(id: number): Observable<Expanded<CharacterBuildTeam, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterBuildTeam, 'created_by' | 'updated_by'>>(`/api/characters-builds-teams/${id}`);
  }

  /**
   * `GET /api/characters-builds-teams-characters/{id}`
   */
  getCharacterBuildTeamCharacter(id: number): Observable<Expanded<CharacterBuildTeamCharacter, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterBuildTeamCharacter, 'created_by' | 'updated_by'>>(`/api/characters-builds-teams-characters/${id}`);
  }

  /**
   * `GET /api/characters-builds-teams-characters`
   */
  getCharacterBuildTeamCharacters(): Observable<Expanded<CharacterBuildTeamCharacter, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterBuildTeamCharacter, 'created_by' | 'updated_by'>[]>('/api/characters-builds-teams-characters');
  }

  /**
   * `GET /api/characters-builds-teams`
   */
  getCharacterBuildTeams(): Observable<Expanded<CharacterBuildTeam, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterBuildTeam, 'created_by' | 'updated_by'>[]>('/api/characters-builds-teams');
  }

  /**
   * `GET /api/characters-builds-weapons/{id}`
   */
  getCharacterBuildWeapon(id: number): Observable<Expanded<CharacterBuildWeapon, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterBuildWeapon, 'created_by' | 'updated_by'>>(`/api/characters-builds-weapons/${id}`);
  }

  /**
   * `GET /api/characters-builds-weapons`
   */
  getCharacterBuildWeapons(): Observable<Expanded<CharacterBuildWeapon, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterBuildWeapon, 'created_by' | 'updated_by'>[]>('/api/characters-builds-weapons');
  }

  /**
   * `GET /api/characters-constellations/{id}`
   */
  getCharacterConstellation(id: number): Observable<Expanded<CharacterConstellation, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterConstellation, 'created_by' | 'updated_by'>>(`/api/characters-constellations/${id}`);
  }

  /**
   * `GET /api/characters-constellations`
   */
  getCharacterConstellations(): Observable<Expanded<CharacterConstellation, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterConstellation, 'created_by' | 'updated_by'>[]>('/api/characters-constellations');
  }

  /**
   * `GET /api/characters/{id}/full`
   */
  getCharacterFull(id: number): Observable<CharacterFull> {
    return this._http.get<CharacterFull>(`/api/characters/${id}/full`);
  }

  /**
   * `GET /api/characters-relationships/{id}`
   */
  getCharacterRelationship(id: number): Observable<Expanded<CharacterRelationship, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterRelationship, 'created_by' | 'updated_by'>>(`/api/characters-relationships/${id}`);
  }

  /**
   * `GET /api/characters-relationships`
   */
  getCharacterRelationships(): Observable<Expanded<CharacterRelationship, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterRelationship, 'created_by' | 'updated_by'>[]>('/api/characters-relationships');
  }

  /**
   * `GET /api/characters-roles/{id}`
   */
  getCharacterRole(id: number): Observable<Expanded<CharacterRole, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterRole, 'created_by' | 'updated_by'>>(`/api/characters-roles/${id}`);
  }

  /**
   * `GET /api/characters-roles`
   */
  getCharacterRoles(): Observable<Expanded<CharacterRole, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterRole, 'created_by' | 'updated_by'>[]>('/api/characters-roles');
  }

  /**
   * `GET /api/characters`
   */
  getCharacters(): Observable<Expanded<Character, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<Character, 'created_by' | 'updated_by'>[]>('/api/characters');
  }

  /**
   * `GET /api/characters/minimal`
   */
  getCharactersMinimal(): Observable<Character[]> {
    return this._http.get<Character[]>('/api/characters/minimal');
  }

  /**
   * `GET /api/characters-talents/{id}`
   */
  getCharacterTalent(id: number): Observable<Expanded<CharacterTalent, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterTalent, 'created_by' | 'updated_by'>>(`/api/characters-talents/${id}`);
  }

  /**
   * `GET /api/characters-talents-cost/{id}`
   */
  getCharacterTalentCost(id: number): Observable<Expanded<CharacterTalentCost, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterTalentCost, 'created_by' | 'updated_by'>>(`/api/characters-talents-cost/${id}`);
  }

  /**
   * `GET /api/characters-talents-cost`
   */
  getCharacterTalentCosts(): Observable<Expanded<CharacterTalentCost, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterTalentCost, 'created_by' | 'updated_by'>[]>('/api/characters-talents-cost');
  }

  /**
   * `GET /api/characters-talents`
   */
  getCharacterTalents(): Observable<Expanded<CharacterTalent, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterTalent, 'created_by' | 'updated_by'>[]>('/api/characters-talents');
  }

  /**
   * `GET /api/characters-voice-overs/{id}`
   */
  getCharacterVoiceOver(id: number): Observable<Expanded<CharacterVoiceOver, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<CharacterVoiceOver, 'created_by' | 'updated_by'>>(`/api/characters-voice-overs/${id}`);
  }

  /**
   * `GET /api/characters-voice-overs`
   */
  getCharacterVoiceOvers(): Observable<Expanded<CharacterVoiceOver, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<CharacterVoiceOver, 'created_by' | 'updated_by'>[]>('/api/characters-voice-overs');
  }

  /**
   * `GET /api/character/random`
   */
  getRandomCharacter(): Observable<Character[]> {
    return this._http.get<Character[]>('/api/character/random');
  }

  /**
   * `PUT /api/characters/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacter(id: number, body: Partial<CharacterPayload>): Observable<Expanded<Character, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<Character, 'created_by' | 'updated_by'>>(`/api/characters/${id}`, body);
  }

  /**
   * `PUT /api/characters-ascensions/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterAscension(id: number, body: Partial<CharacterAscensionPayload>): Observable<Expanded<CharacterAscension, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterAscension, 'created_by' | 'updated_by'>>(`/api/characters-ascensions/${id}`, body);
  }

  /**
   * `PUT /api/characters-ascensions-cost/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterAscensionCost(id: number, body: Partial<CharacterAscensionCostPayload>): Observable<Expanded<CharacterAscensionCost, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterAscensionCost, 'created_by' | 'updated_by'>>(`/api/characters-ascensions-cost/${id}`, body);
  }

  /**
   * `PUT /api/characters-builds/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterBuild(id: number, body: Partial<CharacterBuildPayload>): Observable<Expanded<CharacterBuild, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterBuild, 'created_by' | 'updated_by'>>(`/api/characters-builds/${id}`, body);
  }

  /**
   * `PUT /api/characters-builds-artifacts/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterBuildArtifact(id: number, body: Partial<CharacterBuildArtifactPayload>): Observable<Expanded<CharacterBuildArtifact, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterBuildArtifact, 'created_by' | 'updated_by'>>(`/api/characters-builds-artifacts/${id}`, body);
  }

  /**
   * `PUT /api/characters-builds-main-stats/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterBuildMainStat(id: number, body: Partial<CharacterBuildMainStatPayload>): Observable<Expanded<CharacterBuildMainStat, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterBuildMainStat, 'created_by' | 'updated_by'>>(`/api/characters-builds-main-stats/${id}`, body);
  }

  /**
   * `PUT /api/characters-builds-recommended-stats/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterBuildRecommendedStat(id: number, body: Partial<CharacterBuildRecommendedStatPayload>): Observable<Expanded<CharacterBuildRecommendedStat, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterBuildRecommendedStat, 'created_by' | 'updated_by'>>(`/api/characters-builds-recommended-stats/${id}`, body);
  }

  /**
   * `PUT /api/characters-builds-sub-stats/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterBuildSubStat(id: number, body: Partial<CharacterBuildSubStatPayload>): Observable<Expanded<CharacterBuildSubStat, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterBuildSubStat, 'created_by' | 'updated_by'>>(`/api/characters-builds-sub-stats/${id}`, body);
  }

  /**
   * `PUT /api/characters-builds-talents/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterBuildTalent(id: number, body: Partial<CharacterBuildTalentPayload>): Observable<Expanded<CharacterBuildTalent, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterBuildTalent, 'created_by' | 'updated_by'>>(`/api/characters-builds-talents/${id}`, body);
  }

  /**
   * `PUT /api/characters-builds-teams/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterBuildTeam(id: number, body: Partial<CharacterBuildTeamPayload>): Observable<Expanded<CharacterBuildTeam, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterBuildTeam, 'created_by' | 'updated_by'>>(`/api/characters-builds-teams/${id}`, body);
  }

  /**
   * `PUT /api/characters-builds-teams-characters/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterBuildTeamCharacter(id: number, body: Partial<CharacterBuildTeamCharacterPayload>): Observable<Expanded<CharacterBuildTeamCharacter, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterBuildTeamCharacter, 'created_by' | 'updated_by'>>(`/api/characters-builds-teams-characters/${id}`, body);
  }

  /**
   * `PUT /api/characters-builds-weapons/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterBuildWeapon(id: number, body: Partial<CharacterBuildWeaponPayload>): Observable<Expanded<CharacterBuildWeapon, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterBuildWeapon, 'created_by' | 'updated_by'>>(`/api/characters-builds-weapons/${id}`, body);
  }

  /**
   * `PUT /api/characters-constellations/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterConstellation(id: number, body: Partial<CharacterConstellationPayload>): Observable<Expanded<CharacterConstellation, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterConstellation, 'created_by' | 'updated_by'>>(`/api/characters-constellations/${id}`, body);
  }

  /**
   * `PUT /api/characters/{id}/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterFull(id: number, body: FormData): Observable<Expanded<Character, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<Character, 'created_by' | 'updated_by'>>(`/api/characters/${id}/full`, body);
  }

  /**
   * `PUT /api/characters-relationships/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterRelationship(id: number, body: Partial<CharacterRelationshipPayload>): Observable<Expanded<CharacterRelationship, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterRelationship, 'created_by' | 'updated_by'>>(`/api/characters-relationships/${id}`, body);
  }

  /**
   * `PUT /api/characters-talents/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterTalent(id: number, body: Partial<CharacterTalentPayload>): Observable<Expanded<CharacterTalent, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterTalent, 'created_by' | 'updated_by'>>(`/api/characters-talents/${id}`, body);
  }

  /**
   * `PUT /api/characters-talents-cost/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterTalentCost(id: number, body: Partial<CharacterTalentCostPayload>): Observable<Expanded<CharacterTalentCost, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterTalentCost, 'created_by' | 'updated_by'>>(`/api/characters-talents-cost/${id}`, body);
  }

  /**
   * `PUT /api/characters-voice-overs/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateCharacterVoiceOver(id: number, body: Partial<CharacterVoiceOverPayload>): Observable<Expanded<CharacterVoiceOver, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<CharacterVoiceOver, 'created_by' | 'updated_by'>>(`/api/characters-voice-overs/${id}`, body);
  }
}
