// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { DashboardStats } from '../types';

/**
 * The counts on the admin landing page.
 */
@Injectable({ providedIn: 'root' })
export class DashboardApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `GET /api/dashboard/stats`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getDashboardStats(): Observable<DashboardStats> {
    return this._http.get<DashboardStats>('/api/dashboard/stats');
  }
}
