// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  Enemy,
  EnemyDamageTypeElement,
  EnemyDamageTypeElementPayload,
  EnemyDrop,
  EnemyDropPayload,
  EnemyFull,
  EnemyFullRow,
  EnemyPayload,
  EnemyPhase,
  EnemyPhasePayload,
} from '../models';
import { Expanded } from '../types';

/**
 * Enemies, their phases, their drops and their elemental behaviour.
 */
@Injectable({ providedIn: 'root' })
export class EnemyApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/enemies`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createEnemy(body: EnemyPayload): Observable<Expanded<Enemy, 'created_by'>> {
    return this._http.post<Expanded<Enemy, 'created_by'>>('/api/enemies', body);
  }

  /**
   * `POST /api/enemies-damage-types-elements`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createEnemyDamageTypeElement(body: EnemyDamageTypeElementPayload): Observable<Expanded<EnemyDamageTypeElement, 'created_by'>> {
    return this._http.post<Expanded<EnemyDamageTypeElement, 'created_by'>>('/api/enemies-damage-types-elements', body);
  }

  /**
   * `POST /api/enemies-drops`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createEnemyDrop(body: EnemyDropPayload): Observable<Expanded<EnemyDrop, 'created_by'>> {
    return this._http.post<Expanded<EnemyDrop, 'created_by'>>('/api/enemies-drops', body);
  }

  /**
   * `POST /api/enemies/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createEnemyFull(body: FormData): Observable<Enemy> {
    return this._http.post<Enemy>('/api/enemies/full', body);
  }

  /**
   * `POST /api/enemies-phases`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createEnemyPhase(body: EnemyPhasePayload): Observable<Expanded<EnemyPhase, 'created_by'>> {
    return this._http.post<Expanded<EnemyPhase, 'created_by'>>('/api/enemies-phases', body);
  }

  /**
   * `DELETE /api/enemies/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteEnemy(id: number): Observable<Enemy> {
    return this._http.delete<Enemy>(`/api/enemies/${id}`);
  }

  /**
   * `DELETE /api/enemies-damage-types-elements/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteEnemyDamageTypeElement(id: number): Observable<EnemyDamageTypeElement> {
    return this._http.delete<EnemyDamageTypeElement>(`/api/enemies-damage-types-elements/${id}`);
  }

  /**
   * `DELETE /api/enemies-drops/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteEnemyDrop(id: number): Observable<EnemyDrop> {
    return this._http.delete<EnemyDrop>(`/api/enemies-drops/${id}`);
  }

  /**
   * `DELETE /api/enemies-phases/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteEnemyPhase(id: number): Observable<EnemyPhase> {
    return this._http.delete<EnemyPhase>(`/api/enemies-phases/${id}`);
  }

  /**
   * `GET /api/enemies`
   */
  getEnemies(): Observable<Expanded<Enemy, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<Enemy, 'created_by' | 'updated_by'>[]>('/api/enemies');
  }

  /**
   * `GET /api/enemies/full`
   */
  getEnemiesFull(): Observable<EnemyFullRow[]> {
    return this._http.get<EnemyFullRow[]>('/api/enemies/full');
  }

  /**
   * `GET /api/enemies/{id}`
   */
  getEnemy(id: number): Observable<Expanded<Enemy, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<Enemy, 'created_by' | 'updated_by'>>(`/api/enemies/${id}`);
  }

  /**
   * `GET /api/enemies-damage-types-elements/{id}`
   */
  getEnemyDamageTypeElement(id: number): Observable<Expanded<EnemyDamageTypeElement, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<EnemyDamageTypeElement, 'created_by' | 'updated_by'>>(`/api/enemies-damage-types-elements/${id}`);
  }

  /**
   * `GET /api/enemies-damage-types-elements`
   */
  getEnemyDamageTypeElements(): Observable<Expanded<EnemyDamageTypeElement, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<EnemyDamageTypeElement, 'created_by' | 'updated_by'>[]>('/api/enemies-damage-types-elements');
  }

  /**
   * `GET /api/enemies-drops/{id}`
   */
  getEnemyDrop(id: number): Observable<Expanded<EnemyDrop, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<EnemyDrop, 'created_by' | 'updated_by'>>(`/api/enemies-drops/${id}`);
  }

  /**
   * `GET /api/enemies-drops`
   */
  getEnemyDrops(): Observable<Expanded<EnemyDrop, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<EnemyDrop, 'created_by' | 'updated_by'>[]>('/api/enemies-drops');
  }

  /**
   * `GET /api/enemies/{id}/full`
   */
  getEnemyFull(id: number): Observable<EnemyFull> {
    return this._http.get<EnemyFull>(`/api/enemies/${id}/full`);
  }

  /**
   * `GET /api/enemies-phases/{id}`
   */
  getEnemyPhase(id: number): Observable<Expanded<EnemyPhase, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<EnemyPhase, 'created_by' | 'updated_by'>>(`/api/enemies-phases/${id}`);
  }

  /**
   * `GET /api/enemies-phases`
   */
  getEnemyPhases(): Observable<Expanded<EnemyPhase, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<EnemyPhase, 'created_by' | 'updated_by'>[]>('/api/enemies-phases');
  }

  /**
   * `PUT /api/enemies/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateEnemy(id: number, body: Partial<EnemyPayload>): Observable<Expanded<Enemy, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<Enemy, 'created_by' | 'updated_by'>>(`/api/enemies/${id}`, body);
  }

  /**
   * `PUT /api/enemies-damage-types-elements/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateEnemyDamageTypeElement(id: number, body: Partial<EnemyDamageTypeElementPayload>): Observable<Expanded<EnemyDamageTypeElement, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<EnemyDamageTypeElement, 'created_by' | 'updated_by'>>(`/api/enemies-damage-types-elements/${id}`, body);
  }

  /**
   * `PUT /api/enemies-drops/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateEnemyDrop(id: number, body: Partial<EnemyDropPayload>): Observable<Expanded<EnemyDrop, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<EnemyDrop, 'created_by' | 'updated_by'>>(`/api/enemies-drops/${id}`, body);
  }

  /**
   * `PUT /api/enemies/{id}/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateEnemyFull(id: number, body: FormData): Observable<Enemy> {
    return this._http.put<Enemy>(`/api/enemies/${id}/full`, body);
  }

  /**
   * `PUT /api/enemies-phases/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateEnemyPhase(id: number, body: Partial<EnemyPhasePayload>): Observable<Expanded<EnemyPhase, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<EnemyPhase, 'created_by' | 'updated_by'>>(`/api/enemies-phases/${id}`, body);
  }
}
