// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { ApiMessage, Feedback, FeedbackFilters, FeedbackPage, FeedbackStatusChanged } from '../models';
import { FeedbackQuery, FeedbackRequest, FeedbackStatusRequest } from '../types';
import { toHttpParams } from '../http-params';

/**
 * Messages sent from the site's contact form.
 */
@Injectable({ providedIn: 'root' })
export class FeedbackApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `DELETE /api/feedback/{id}`
   *
   * Requires the `ADMIN` role.
   */
  deleteFeedbackEntry(id: number): Observable<Feedback> {
    return this._http.delete<Feedback>(`/api/feedback/${id}`);
  }

  /**
   * `GET /api/feedback/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getFeedbackEntry(id: number): Observable<Feedback> {
    return this._http.get<Feedback>(`/api/feedback/${id}`);
  }

  /**
   * `GET /api/feedback/filters`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getFeedbackFilters(): Observable<FeedbackFilters> {
    return this._http.get<FeedbackFilters>('/api/feedback/filters');
  }

  /**
   * `GET /api/feedback`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getFeedbackPage(params?: FeedbackQuery): Observable<FeedbackPage> {
    return this._http.get<FeedbackPage>('/api/feedback', { params: toHttpParams(params) });
  }

  /**
   * `POST /api/feedback`
   */
  sendFeedback(body: FeedbackRequest): Observable<ApiMessage> {
    return this._http.post<ApiMessage>('/api/feedback', body);
  }

  /**
   * `PUT /api/feedback/{id}/status`
   *
   * Requires the `ADMIN` role.
   */
  updateFeedbackStatus(id: number, body: FeedbackStatusRequest): Observable<FeedbackStatusChanged> {
    return this._http.put<FeedbackStatusChanged>(`/api/feedback/${id}/status`, body);
  }
}
