// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { FileCategory } from '../models';
import { FileCategoryCreateRequest, FileCategorySaveRequest } from '../types';

/**
 * The kinds of asset there are, and which folder each kind lives in.
 */
@Injectable({ providedIn: 'root' })
export class FileCategoryApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/file-categories`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  addFileCategory(body: FileCategoryCreateRequest): Observable<FileCategory[]> {
    return this._http.post<FileCategory[]>('/api/file-categories', body);
  }

  /**
   * `GET /api/file-categories`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getFileCategories(): Observable<FileCategory[]> {
    return this._http.get<FileCategory[]>('/api/file-categories');
  }

  /**
   * `DELETE /api/file-categories/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  retireFileCategory(id: number): Observable<FileCategory[]> {
    return this._http.delete<FileCategory[]>(`/api/file-categories/${id}`);
  }

  /**
   * `PUT /api/file-categories/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  saveFileCategory(id: number, body: FileCategorySaveRequest): Observable<FileCategory[]> {
    return this._http.put<FileCategory[]>(`/api/file-categories/${id}`, body);
  }
}
