// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  AssetConvertProgress,
  AssetFilePage,
  AssetFolder,
  AssetRestoreResult,
  AssetStats,
  AssetTrashResult,
  AssetUploadResult,
  EntityUploadResult,
  RecordUploadResult,
  TrashedFile,
  UploadResult,
} from '../models';
import { AssetConvertRequest, AssetFileQuery, AssetFileRef, AssetStatsQuery } from '../types';
import { toHttpParams } from '../http-params';

/**
 * The asset tree on disk: browsing it, adding to it, and undoing a deletion.
 */
@Injectable({ providedIn: 'root' })
export class FileApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/files/convert`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  convertAssets(body: AssetConvertRequest): Observable<AssetConvertProgress> {
    return this._http.post<AssetConvertProgress>('/api/files/convert', body);
  }

  /**
   * `DELETE /api/files`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteAssetFile(params: AssetFileRef): Observable<AssetTrashResult> {
    return this._http.delete<AssetTrashResult>('/api/files', { params: toHttpParams(params) });
  }

  /**
   * `GET /api/files`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getAssetFiles(params: AssetFileQuery): Observable<AssetFilePage> {
    return this._http.get<AssetFilePage>('/api/files', { params: toHttpParams(params) });
  }

  /**
   * `GET /api/files/folders`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getAssetFolders(): Observable<AssetFolder[]> {
    return this._http.get<AssetFolder[]>('/api/files/folders');
  }

  /**
   * `GET /api/files/stats`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getAssetStats(params?: AssetStatsQuery): Observable<AssetStats> {
    return this._http.get<AssetStats>('/api/files/stats', { params: toHttpParams(params) });
  }

  /**
   * `GET /api/files/convert`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getConversionProgress(): Observable<AssetConvertProgress> {
    return this._http.get<AssetConvertProgress>('/api/files/convert');
  }

  /**
   * `GET /api/files/trash`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getTrashedFiles(): Observable<TrashedFile[]> {
    return this._http.get<TrashedFile[]>('/api/files/trash');
  }

  /**
   * `POST /api/files/restore`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  restoreAssetFile(body: FormData): Observable<AssetRestoreResult> {
    return this._http.post<AssetRestoreResult>('/api/files/restore', body);
  }

  /**
   * `POST /api/files`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  uploadAssetFile(body: FormData): Observable<AssetUploadResult> {
    return this._http.post<AssetUploadResult>('/api/files', body);
  }

  /**
   * `POST /api/uploads/{entity}/{field}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  uploadEntityFile(entity: string, field: string, body: FormData): Observable<EntityUploadResult> {
    return this._http.post<EntityUploadResult>(`/api/uploads/${encodeURIComponent(entity)}/${encodeURIComponent(field)}`, body);
  }

  /**
   * `POST /api/upload`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  uploadFile(body: FormData): Observable<UploadResult> {
    return this._http.post<UploadResult>('/api/upload', body);
  }

  /**
   * `POST /api/uploads/{entity}/{id}/{field}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  uploadRecordFile(entity: string, id: number, field: string, body: FormData): Observable<RecordUploadResult> {
    return this._http.post<RecordUploadResult>(`/api/uploads/${encodeURIComponent(entity)}/${id}/${encodeURIComponent(field)}`, body);
  }
}
