// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Food, FoodFull, FoodFullRow, FoodPayload, FoodRecipe, FoodRecipePayload } from '../models';
import { Expanded } from '../types';

/**
 * Dishes and their recipes.
 */
@Injectable({ providedIn: 'root' })
export class FoodApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/foods`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createFood(body: FoodPayload): Observable<Expanded<Food, 'created_by'>> {
    return this._http.post<Expanded<Food, 'created_by'>>('/api/foods', body);
  }

  /**
   * `POST /api/foods/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createFoodFull(body: FormData): Observable<Food> {
    return this._http.post<Food>('/api/foods/full', body);
  }

  /**
   * `POST /api/foods-recipe`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createFoodRecipe(body: FoodRecipePayload): Observable<Expanded<FoodRecipe, 'created_by'>> {
    return this._http.post<Expanded<FoodRecipe, 'created_by'>>('/api/foods-recipe', body);
  }

  /**
   * `DELETE /api/foods/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteFood(id: number): Observable<Food> {
    return this._http.delete<Food>(`/api/foods/${id}`);
  }

  /**
   * `DELETE /api/foods-recipe/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteFoodRecipe(id: number): Observable<FoodRecipe> {
    return this._http.delete<FoodRecipe>(`/api/foods-recipe/${id}`);
  }

  /**
   * `GET /api/foods/{id}`
   */
  getFood(id: number): Observable<Expanded<Food, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<Food, 'created_by' | 'updated_by'>>(`/api/foods/${id}`);
  }

  /**
   * `GET /api/foods/{id}/full`
   */
  getFoodFull(id: number): Observable<FoodFull> {
    return this._http.get<FoodFull>(`/api/foods/${id}/full`);
  }

  /**
   * `GET /api/foods-recipe/{id}`
   */
  getFoodRecipe(id: number): Observable<Expanded<FoodRecipe, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<FoodRecipe, 'created_by' | 'updated_by'>>(`/api/foods-recipe/${id}`);
  }

  /**
   * `GET /api/foods-recipe`
   */
  getFoodRecipes(): Observable<Expanded<FoodRecipe, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<FoodRecipe, 'created_by' | 'updated_by'>[]>('/api/foods-recipe');
  }

  /**
   * `GET /api/foods`
   */
  getFoods(): Observable<Expanded<Food, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<Food, 'created_by' | 'updated_by'>[]>('/api/foods');
  }

  /**
   * `GET /api/foods/full`
   */
  getFoodsFull(): Observable<FoodFullRow[]> {
    return this._http.get<FoodFullRow[]>('/api/foods/full');
  }

  /**
   * `PUT /api/foods/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateFood(id: number, body: Partial<FoodPayload>): Observable<Expanded<Food, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<Food, 'created_by' | 'updated_by'>>(`/api/foods/${id}`, body);
  }

  /**
   * `PUT /api/foods/{id}/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateFoodFull(id: number, body: FormData): Observable<Food> {
    return this._http.put<Food>(`/api/foods/${id}/full`, body);
  }

  /**
   * `PUT /api/foods-recipe/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateFoodRecipe(id: number, body: Partial<FoodRecipePayload>): Observable<Expanded<FoodRecipe, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<FoodRecipe, 'created_by' | 'updated_by'>>(`/api/foods-recipe/${id}`, body);
  }
}
