// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

export * from './artifact.service';
export * from './audit-log.service';
export * from './auth.service';
export * from './background.service';
export * from './backup.service';
export * from './banner.service';
export * from './character.service';
export * from './dashboard.service';
export * from './enemy.service';
export * from './feedback.service';
export * from './file.service';
export * from './food.service';
export * from './language.service';
export * from './lookup.service';
export * from './material.service';
export * from './migration.service';
export * from './quiz.service';
export * from './session.service';
export * from './setting.service';
export * from './stat.service';
export * from './translation.service';
export * from './user.service';
export * from './weapon.service';
