// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Language, LanguagePayload } from '../models';
import { LanguageDeleted, LanguageQuery } from '../types';
import { toHttpParams } from '../http-params';

/**
 * Which languages the site offers, and which of them is the fallback.
 */
@Injectable({ providedIn: 'root' })
export class LanguageApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/languages`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createLanguage(body: LanguagePayload): Observable<Language> {
    return this._http.post<Language>('/api/languages', body);
  }

  /**
   * `DELETE /api/languages/{code}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteLanguage(code: string): Observable<LanguageDeleted> {
    return this._http.delete<LanguageDeleted>(`/api/languages/${encodeURIComponent(code)}`);
  }

  /**
   * `GET /api/languages`
   */
  getLanguages(params?: LanguageQuery): Observable<Language[]> {
    return this._http.get<Language[]>('/api/languages', { params: toHttpParams(params) });
  }

  /**
   * `PUT /api/languages/{code}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateLanguage(code: string, body: Partial<LanguagePayload>): Observable<Language> {
    return this._http.put<Language>(`/api/languages/${encodeURIComponent(code)}`, body);
  }
}
