// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  ArtifactPieceType,
  CharacterModel,
  CharacterState,
  DomainLevel,
  DomainLevelPayload,
  Element,
  EnemyFamily,
  EnemyFamilyPayload,
  EnemyGroup,
  EnemyGroupPayload,
  EnemyType,
  EnemyTypePayload,
  FoodType,
  FoodTypePayload,
  MaterialGroup,
  MaterialGroupPayload,
  MaterialType,
  MaterialTypePayload,
  Rarity,
  Region,
  RegionPayload,
  RelationshipType,
  RelationshipTypePayload,
  Role,
  RolePayload,
  TalentType,
  TalentTypePayload,
  VoiceOverType,
  WeaponType,
} from '../models';

/**
 * The name-keyed lookup tables. Every one is a list of `{ name }`, read to fill a dropdown.
 */
@Injectable({ providedIn: 'root' })
export class LookupApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/domain-levels`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createDomainLevel(body: DomainLevelPayload): Observable<DomainLevel> {
    return this._http.post<DomainLevel>('/api/domain-levels', body);
  }

  /**
   * `POST /api/enemy-families`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createEnemyFamily(body: EnemyFamilyPayload): Observable<EnemyFamily> {
    return this._http.post<EnemyFamily>('/api/enemy-families', body);
  }

  /**
   * `POST /api/enemy-groups`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createEnemyGroup(body: EnemyGroupPayload): Observable<EnemyGroup> {
    return this._http.post<EnemyGroup>('/api/enemy-groups', body);
  }

  /**
   * `POST /api/enemy-types`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createEnemyType(body: EnemyTypePayload): Observable<EnemyType> {
    return this._http.post<EnemyType>('/api/enemy-types', body);
  }

  /**
   * `POST /api/food-types`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createFoodType(body: FoodTypePayload): Observable<FoodType> {
    return this._http.post<FoodType>('/api/food-types', body);
  }

  /**
   * `POST /api/material-groups`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createMaterialGroup(body: MaterialGroupPayload): Observable<MaterialGroup> {
    return this._http.post<MaterialGroup>('/api/material-groups', body);
  }

  /**
   * `POST /api/material-types`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createMaterialType(body: MaterialTypePayload): Observable<MaterialType> {
    return this._http.post<MaterialType>('/api/material-types', body);
  }

  /**
   * `POST /api/regions`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createRegion(body: RegionPayload): Observable<Region> {
    return this._http.post<Region>('/api/regions', body);
  }

  /**
   * `POST /api/relationship-types`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createRelationshipType(body: RelationshipTypePayload): Observable<RelationshipType> {
    return this._http.post<RelationshipType>('/api/relationship-types', body);
  }

  /**
   * `POST /api/roles`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createRole(body: RolePayload): Observable<Role> {
    return this._http.post<Role>('/api/roles', body);
  }

  /**
   * `POST /api/talent-types`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createTalentType(body: TalentTypePayload): Observable<TalentType> {
    return this._http.post<TalentType>('/api/talent-types', body);
  }

  /**
   * `DELETE /api/domain-levels/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteDomainLevel(name: string): Observable<DomainLevel> {
    return this._http.delete<DomainLevel>(`/api/domain-levels/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/enemy-families/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteEnemyFamily(name: string): Observable<EnemyFamily> {
    return this._http.delete<EnemyFamily>(`/api/enemy-families/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/enemy-groups/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteEnemyGroup(name: string): Observable<EnemyGroup> {
    return this._http.delete<EnemyGroup>(`/api/enemy-groups/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/enemy-types/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteEnemyType(name: string): Observable<EnemyType> {
    return this._http.delete<EnemyType>(`/api/enemy-types/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/food-types/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteFoodType(name: string): Observable<FoodType> {
    return this._http.delete<FoodType>(`/api/food-types/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/material-groups/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteMaterialGroup(name: string): Observable<MaterialGroup> {
    return this._http.delete<MaterialGroup>(`/api/material-groups/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/material-types/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteMaterialType(name: string): Observable<MaterialType> {
    return this._http.delete<MaterialType>(`/api/material-types/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/regions/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteRegion(name: string): Observable<Region> {
    return this._http.delete<Region>(`/api/regions/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/relationship-types/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteRelationshipType(name: string): Observable<RelationshipType> {
    return this._http.delete<RelationshipType>(`/api/relationship-types/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/roles/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteRole(name: string): Observable<Role> {
    return this._http.delete<Role>(`/api/roles/${encodeURIComponent(name)}`);
  }

  /**
   * `DELETE /api/talent-types/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteTalentType(name: string): Observable<TalentType> {
    return this._http.delete<TalentType>(`/api/talent-types/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/artifact-piece-types`
   */
  getArtifactPieceTypes(): Observable<ArtifactPieceType[]> {
    return this._http.get<ArtifactPieceType[]>('/api/artifact-piece-types');
  }

  /**
   * `GET /api/domain-levels/{name}`
   */
  getDomainLevel(name: string): Observable<DomainLevel> {
    return this._http.get<DomainLevel>(`/api/domain-levels/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/domain-levels`
   */
  getDomainLevels(): Observable<DomainLevel[]> {
    return this._http.get<DomainLevel[]>('/api/domain-levels');
  }

  /**
   * `GET /api/elements`
   */
  getElements(): Observable<Element[]> {
    return this._http.get<Element[]>('/api/elements');
  }

  /**
   * `GET /api/enemy-families`
   */
  getEnemyFamilies(): Observable<EnemyFamily[]> {
    return this._http.get<EnemyFamily[]>('/api/enemy-families');
  }

  /**
   * `GET /api/enemy-families/{name}`
   */
  getEnemyFamily(name: string): Observable<EnemyFamily> {
    return this._http.get<EnemyFamily>(`/api/enemy-families/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/enemy-groups/{name}`
   */
  getEnemyGroup(name: string): Observable<EnemyGroup> {
    return this._http.get<EnemyGroup>(`/api/enemy-groups/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/enemy-groups`
   */
  getEnemyGroups(): Observable<EnemyGroup[]> {
    return this._http.get<EnemyGroup[]>('/api/enemy-groups');
  }

  /**
   * `GET /api/enemy-types/{name}`
   */
  getEnemyType(name: string): Observable<EnemyType> {
    return this._http.get<EnemyType>(`/api/enemy-types/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/enemy-types`
   */
  getEnemyTypes(): Observable<EnemyType[]> {
    return this._http.get<EnemyType[]>('/api/enemy-types');
  }

  /**
   * `GET /api/food-types/{name}`
   */
  getFoodType(name: string): Observable<FoodType> {
    return this._http.get<FoodType>(`/api/food-types/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/food-types`
   */
  getFoodTypes(): Observable<FoodType[]> {
    return this._http.get<FoodType[]>('/api/food-types');
  }

  /**
   * `GET /api/character-models`
   */
  getCharacterModels(): Observable<CharacterModel[]> {
    return this._http.get<CharacterModel[]>('/api/character-models');
  }

  /**
   * `GET /api/character-states`
   */
  getCharacterStates(): Observable<CharacterState[]> {
    return this._http.get<CharacterState[]>('/api/character-states');
  }

  /**
   * `GET /api/material-groups/{name}`
   */
  getMaterialGroup(name: string): Observable<MaterialGroup> {
    return this._http.get<MaterialGroup>(`/api/material-groups/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/material-groups`
   */
  getMaterialGroups(): Observable<MaterialGroup[]> {
    return this._http.get<MaterialGroup[]>('/api/material-groups');
  }

  /**
   * `GET /api/material-types/{name}`
   */
  getMaterialType(name: string): Observable<MaterialType> {
    return this._http.get<MaterialType>(`/api/material-types/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/material-types`
   */
  getMaterialTypes(): Observable<MaterialType[]> {
    return this._http.get<MaterialType[]>('/api/material-types');
  }

  /**
   * `GET /api/rarities`
   */
  getRarities(): Observable<Rarity[]> {
    return this._http.get<Rarity[]>('/api/rarities');
  }

  /**
   * `GET /api/regions/{name}`
   */
  getRegion(name: string): Observable<Region> {
    return this._http.get<Region>(`/api/regions/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/regions`
   */
  getRegions(): Observable<Region[]> {
    return this._http.get<Region[]>('/api/regions');
  }

  /**
   * `GET /api/relationship-types/{name}`
   */
  getRelationshipType(name: string): Observable<RelationshipType> {
    return this._http.get<RelationshipType>(`/api/relationship-types/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/relationship-types`
   */
  getRelationshipTypes(): Observable<RelationshipType[]> {
    return this._http.get<RelationshipType[]>('/api/relationship-types');
  }

  /**
   * `GET /api/roles/{name}`
   */
  getRole(name: string): Observable<Role> {
    return this._http.get<Role>(`/api/roles/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/roles`
   */
  getRoles(): Observable<Role[]> {
    return this._http.get<Role[]>('/api/roles');
  }

  /**
   * `GET /api/talent-types/{name}`
   */
  getTalentType(name: string): Observable<TalentType> {
    return this._http.get<TalentType>(`/api/talent-types/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/talent-types`
   */
  getTalentTypes(): Observable<TalentType[]> {
    return this._http.get<TalentType[]>('/api/talent-types');
  }

  /**
   * `GET /api/voice-over-types`
   */
  getVoiceOverTypes(): Observable<VoiceOverType[]> {
    return this._http.get<VoiceOverType[]>('/api/voice-over-types');
  }

  /**
   * `GET /api/weapon-types`
   */
  getWeaponTypes(): Observable<WeaponType[]> {
    return this._http.get<WeaponType[]>('/api/weapon-types');
  }
}
