// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  Material,
  MaterialFull,
  MaterialFullRow,
  MaterialGroupJoin,
  MaterialGroupJoinPayload,
  MaterialPayload,
  MaterialUsage,
} from '../models';
import { Expanded } from '../types';

/**
 * Materials, the groups they belong to, and where each one is spent.
 */
@Injectable({ providedIn: 'root' })
export class MaterialApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/materials`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createMaterial(body: MaterialPayload): Observable<Expanded<Material, 'created_by'>> {
    return this._http.post<Expanded<Material, 'created_by'>>('/api/materials', body);
  }

  /**
   * `POST /api/materials/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createMaterialFull(body: FormData): Observable<Material> {
    return this._http.post<Material>('/api/materials/full', body);
  }

  /**
   * `POST /api/materials-groups-join`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createMaterialGroupJoin(body: MaterialGroupJoinPayload): Observable<Expanded<MaterialGroupJoin, 'created_by'>> {
    return this._http.post<Expanded<MaterialGroupJoin, 'created_by'>>('/api/materials-groups-join', body);
  }

  /**
   * `DELETE /api/materials/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteMaterial(id: number): Observable<Material> {
    return this._http.delete<Material>(`/api/materials/${id}`);
  }

  /**
   * `DELETE /api/materials-groups-join/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteMaterialGroupJoin(id: number): Observable<MaterialGroupJoin> {
    return this._http.delete<MaterialGroupJoin>(`/api/materials-groups-join/${id}`);
  }

  /**
   * `GET /api/materials/{id}`
   */
  getMaterial(id: number): Observable<Expanded<Material, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<Material, 'created_by' | 'updated_by'>>(`/api/materials/${id}`);
  }

  /**
   * `GET /api/materials/by-name/{name}`
   */
  getMaterialByName(name: string): Observable<Material> {
    return this._http.get<Material>(`/api/materials/by-name/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/materials/{id}/full`
   */
  getMaterialFull(id: number): Observable<MaterialFull> {
    return this._http.get<MaterialFull>(`/api/materials/${id}/full`);
  }

  /**
   * `GET /api/materials-groups-join/{id}`
   */
  getMaterialGroupJoin(id: number): Observable<Expanded<MaterialGroupJoin, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<MaterialGroupJoin, 'created_by' | 'updated_by'>>(`/api/materials-groups-join/${id}`);
  }

  /**
   * `GET /api/materials-groups-join`
   */
  getMaterialGroupJoins(): Observable<Expanded<MaterialGroupJoin, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<MaterialGroupJoin, 'created_by' | 'updated_by'>[]>('/api/materials-groups-join');
  }

  /**
   * `GET /api/materials`
   */
  getMaterials(): Observable<Expanded<Material, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<Material, 'created_by' | 'updated_by'>[]>('/api/materials');
  }

  /**
   * `GET /api/materials/full`
   */
  getMaterialsFull(): Observable<MaterialFullRow[]> {
    return this._http.get<MaterialFullRow[]>('/api/materials/full');
  }

  /**
   * `GET /api/materials/{id}/usage`
   */
  getMaterialUsage(id: number): Observable<MaterialUsage> {
    return this._http.get<MaterialUsage>(`/api/materials/${id}/usage`);
  }

  /**
   * `PUT /api/materials/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateMaterial(id: number, body: Partial<MaterialPayload>): Observable<Expanded<Material, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<Material, 'created_by' | 'updated_by'>>(`/api/materials/${id}`, body);
  }

  /**
   * `PUT /api/materials/{id}/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateMaterialFull(id: number, body: FormData): Observable<Material> {
    return this._http.put<Material>(`/api/materials/${id}/full`, body);
  }

  /**
   * `PUT /api/materials-groups-join/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateMaterialGroupJoin(id: number, body: Partial<MaterialGroupJoinPayload>): Observable<Expanded<MaterialGroupJoin, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<MaterialGroupJoin, 'created_by' | 'updated_by'>>(`/api/materials-groups-join/${id}`, body);
  }
}
