// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { MigrationEntry, MigrationFile } from '../models';
import { MigrationFileQuery } from '../types';
import { toHttpParams } from '../http-params';

/**
 * Which migrations have run against which database.
 */
@Injectable({ providedIn: 'root' })
export class MigrationApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `GET /api/migrations/file`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getMigrationFile(params: MigrationFileQuery): Observable<MigrationFile> {
    return this._http.get<MigrationFile>('/api/migrations/file', { params: toHttpParams(params) });
  }

  /**
   * `GET /api/migrations`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getMigrations(): Observable<MigrationEntry[]> {
    return this._http.get<MigrationEntry[]>('/api/migrations');
  }
}
