// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  Quiz,
  QuizHistory,
  QuizPayload,
  QuizState,
  QuizStatePayload,
  QuizStatsHistory,
  QuizStatsHistoryPayload,
  UserQuizHistoryPayload,
} from '../models';
import {
  ApiMessage,
  QuizProgress,
  QuizProgressDeleted,
  QuizProgressRequest,
  QuizProgressSaved,
  QuizResultAck,
  QuizResultRequest,
  QuizStats,
  QuizVoiceOverRound,
} from '../types';

/**
 * The quizzes, a player's progress through them, and the history behind the stats.
 */
@Injectable({ providedIn: 'root' })
export class QuizApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/quizzes`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createQuiz(body: QuizPayload): Observable<Quiz> {
    return this._http.post<Quiz>('/api/quizzes', body);
  }

  /**
   * `POST /api/user-quiz-history`
   *
   * Requires a signed-in user.
   */
  createQuizHistory(body: UserQuizHistoryPayload): Observable<QuizHistory> {
    return this._http.post<QuizHistory>('/api/user-quiz-history', body);
  }

  /**
   * `POST /api/quiz-states`
   *
   * Requires a signed-in user.
   */
  createQuizState(body: QuizStatePayload): Observable<QuizState> {
    return this._http.post<QuizState>('/api/quiz-states', body);
  }

  /**
   * `POST /api/quiz-stats-history`
   *
   * Requires a signed-in user.
   */
  createQuizStatsHistory(body: QuizStatsHistoryPayload): Observable<QuizStatsHistory> {
    return this._http.post<QuizStatsHistory>('/api/quiz-stats-history', body);
  }

  /**
   * `DELETE /api/quizzes/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteQuiz(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/quizzes/${id}`);
  }

  /**
   * `DELETE /api/user-quiz-history/{id}`
   *
   * Requires the `ADMIN` role.
   */
  deleteQuizHistory(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/user-quiz-history/${id}`);
  }

  /**
   * `DELETE /api/quiz/progress/{quiz}`
   *
   * Requires a signed-in user.
   */
  deleteQuizProgress(quiz: string): Observable<QuizProgressDeleted> {
    return this._http.delete<QuizProgressDeleted>(`/api/quiz/progress/${encodeURIComponent(quiz)}`);
  }

  /**
   * `DELETE /api/quiz-states/{user_id}/{quiz_id}`
   *
   * Requires a signed-in user.
   */
  deleteQuizState(userId: number, quizId: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/quiz-states/${userId}/${quizId}`);
  }

  /**
   * `DELETE /api/quiz-stats-history/{user_id}/{character_id}/{quiz_id}`
   *
   * Requires a signed-in user.
   */
  deleteQuizStatsHistory(userId: number, characterId: number, quizId: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/quiz-stats-history/${userId}/${characterId}/${quizId}`);
  }

  /**
   * `GET /api/quizzes/{id}`
   */
  getQuiz(id: number): Observable<Quiz> {
    return this._http.get<Quiz>(`/api/quizzes/${id}`);
  }

  /**
   * `GET /api/user-quiz-history`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getQuizHistories(): Observable<QuizHistory[]> {
    return this._http.get<QuizHistory[]>('/api/user-quiz-history');
  }

  /**
   * `GET /api/user-quiz-history/{id}`
   *
   * Requires a signed-in user.
   */
  getQuizHistory(id: number): Observable<QuizHistory> {
    return this._http.get<QuizHistory>(`/api/user-quiz-history/${id}`);
  }

  /**
   * `GET /api/quiz/progress`
   *
   * Requires a signed-in user.
   */
  getQuizProgress(): Observable<QuizProgress[]> {
    return this._http.get<QuizProgress[]>('/api/quiz/progress');
  }

  /**
   * `GET /api/quiz-states/{user_id}/{quiz_id}`
   *
   * Requires a signed-in user.
   */
  getQuizState(userId: number, quizId: number): Observable<QuizState> {
    return this._http.get<QuizState>(`/api/quiz-states/${userId}/${quizId}`);
  }

  /**
   * `GET /api/quiz-states`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getQuizStates(): Observable<QuizState[]> {
    return this._http.get<QuizState[]>('/api/quiz-states');
  }

  /**
   * `GET /api/quiz/stats`
   *
   * Requires a signed-in user.
   */
  getQuizStats(): Observable<QuizStats> {
    return this._http.get<QuizStats>('/api/quiz/stats');
  }

  /**
   * `GET /api/quiz-stats-history`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getQuizStatsHistories(): Observable<QuizStatsHistory[]> {
    return this._http.get<QuizStatsHistory[]>('/api/quiz-stats-history');
  }

  /**
   * `GET /api/quiz-stats-history/{user_id}/{character_id}/{quiz_id}`
   *
   * Requires a signed-in user.
   */
  getQuizStatsHistory(userId: number, characterId: number, quizId: number): Observable<QuizStatsHistory> {
    return this._http.get<QuizStatsHistory>(`/api/quiz-stats-history/${userId}/${characterId}/${quizId}`);
  }

  /**
   * `GET /api/quizzes`
   */
  getQuizzes(): Observable<Quiz[]> {
    return this._http.get<Quiz[]>('/api/quizzes');
  }

  /**
   * `GET /api/quiz/voice-over/random`
   */
  getRandomVoiceOverRound(): Observable<QuizVoiceOverRound> {
    return this._http.get<QuizVoiceOverRound>('/api/quiz/voice-over/random');
  }

  /**
   * `POST /api/quiz/result`
   *
   * Requires a signed-in user.
   */
  submitQuizResult(body: QuizResultRequest): Observable<QuizResultAck> {
    return this._http.post<QuizResultAck>('/api/quiz/result', body);
  }

  /**
   * `PUT /api/quizzes/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateQuiz(id: number, body: Partial<QuizPayload>): Observable<Quiz> {
    return this._http.put<Quiz>(`/api/quizzes/${id}`, body);
  }

  /**
   * `PUT /api/quiz/progress/{quiz}`
   *
   * Requires a signed-in user.
   */
  updateQuizProgress(quiz: string, body: QuizProgressRequest): Observable<QuizProgressSaved> {
    return this._http.put<QuizProgressSaved>(`/api/quiz/progress/${encodeURIComponent(quiz)}`, body);
  }

  /**
   * `PUT /api/quiz-states/{user_id}/{quiz_id}`
   *
   * Requires a signed-in user.
   */
  updateQuizState(userId: number, quizId: number, body: Partial<QuizStatePayload>): Observable<QuizState> {
    return this._http.put<QuizState>(`/api/quiz-states/${userId}/${quizId}`, body);
  }

  /**
   * `PUT /api/quiz-stats-history/{user_id}/{character_id}/{quiz_id}`
   *
   * Requires a signed-in user.
   */
  updateQuizStatsHistory(userId: number, characterId: number, quizId: number, body: Partial<QuizStatsHistoryPayload>): Observable<QuizStatsHistory> {
    return this._http.put<QuizStatsHistory>(`/api/quiz-stats-history/${userId}/${characterId}/${quizId}`, body);
  }
}
