// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { SiteRouteList } from '../models';
import { SiteRouteCreateRequest, SiteRoutesSaveRequest } from '../types';

/**
 * Which pages of the site exist, who they are drawn for, and which API paths go dark with them.
 */
@Injectable({ providedIn: 'root' })
export class RouteApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/routes`
   *
   * Requires the `ADMIN` role.
   */
  addRoute(body: SiteRouteCreateRequest): Observable<SiteRouteList> {
    return this._http.post<SiteRouteList>('/api/routes', body);
  }

  /**
   * `DELETE /api/routes/{id}`
   *
   * Requires the `ADMIN` role.
   */
  deleteRoute(id: number): Observable<SiteRouteList> {
    return this._http.delete<SiteRouteList>(`/api/routes/${id}`);
  }

  /**
   * `GET /api/routes`
   *
   * Requires the `ADMIN` role.
   */
  getRoutes(): Observable<SiteRouteList> {
    return this._http.get<SiteRouteList>('/api/routes');
  }

  /**
   * `PUT /api/routes`
   *
   * Requires the `ADMIN` role.
   */
  saveRoutes(body: SiteRoutesSaveRequest): Observable<SiteRouteList> {
    return this._http.put<SiteRouteList>('/api/routes', body);
  }
}
