// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { AdminSessionList, ApiMessage } from '../models';
import { SessionHistoryQuery } from '../types';
import { toHttpParams } from '../http-params';

/**
 * Every session anybody has had here: who signed in, from where, and which are still live.
 */
@Injectable({ providedIn: 'root' })
export class SessionApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `DELETE /api/sessions/{id}`
   *
   * Requires the `ADMIN` role.
   */
  endUserSession(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/sessions/${id}`);
  }

  /**
   * `GET /api/sessions`
   *
   * Requires the `ADMIN` role.
   */
  getSessionHistory(params?: SessionHistoryQuery): Observable<AdminSessionList> {
    return this._http.get<AdminSessionList>('/api/sessions', { params: toHttpParams(params) });
  }
}
