// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { PublicSiteSettings, SiteSettingList } from '../models';
import { SiteSettingsSaveRequest } from '../types';

/**
 * The switches an admin can throw without a deploy - maintenance, sign-in, the announcement bar.
 */
@Injectable({ providedIn: 'root' })
export class SettingApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `GET /api/settings/public`
   */
  getPublicSettings(): Observable<PublicSiteSettings> {
    return this._http.get<PublicSiteSettings>('/api/settings/public');
  }

  /**
   * `GET /api/settings`
   *
   * Requires the `ADMIN` role.
   */
  getSettings(): Observable<SiteSettingList> {
    return this._http.get<SiteSettingList>('/api/settings');
  }

  /**
   * `PUT /api/settings`
   *
   * Requires the `ADMIN` role.
   */
  saveSettings(body: SiteSettingsSaveRequest): Observable<SiteSettingList> {
    return this._http.put<SiteSettingList>('/api/settings', body);
  }
}
