// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Stat, StatPayload } from '../models';

/**
 * The stat names the rest of the data refers to.
 */
@Injectable({ providedIn: 'root' })
export class StatApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/stats`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createStat(body: StatPayload): Observable<Stat> {
    return this._http.post<Stat>('/api/stats', body);
  }

  /**
   * `DELETE /api/stats/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteStat(name: string): Observable<Stat> {
    return this._http.delete<Stat>(`/api/stats/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/stats/{name}`
   */
  getStat(name: string): Observable<Stat> {
    return this._http.get<Stat>(`/api/stats/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/stats`
   */
  getStats(): Observable<Stat[]> {
    return this._http.get<Stat[]>('/api/stats');
  }
}
