// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Stat, StatPayload } from '../models';
import { ApiMessage } from '../types';

/**
 * The stat names the rest of the data refers to.
 */
@Injectable({ providedIn: 'root' })
export class StatApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/stats`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createStat(body: StatPayload): Observable<Stat> {
    return this._http.post<Stat>('/api/stats', body);
  }

  /**
   * `DELETE /api/stats/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteStat(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/stats/${id}`);
  }

  /**
   * `GET /api/stats/{id}`
   */
  getStat(id: number): Observable<Stat> {
    return this._http.get<Stat>(`/api/stats/${id}`);
  }

  /**
   * `GET /api/stats`
   */
  getStats(): Observable<Stat[]> {
    return this._http.get<Stat[]>('/api/stats');
  }

  /**
   * `PUT /api/stats/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateStat(id: number, body: Partial<StatPayload>): Observable<Stat> {
    return this._http.put<Stat>(`/api/stats/${id}`, body);
  }
}
