// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { TranslationKey, TranslationKeyPayload } from '../models';
import {
  TranslationAdminView,
  TranslationBundle,
  TranslationBundleResponse,
  TranslationImportRequest,
  TranslationImportResult,
  TranslationKeyDeleted,
  TranslationSaveRequest,
  TranslationSaveResult,
} from '../types';

/**
 * Translation keys and their strings, per language.
 */
@Injectable({ providedIn: 'root' })
export class TranslationApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/translation-keys`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createTranslationKey(body: TranslationKeyPayload): Observable<TranslationKey> {
    return this._http.post<TranslationKey>('/api/translation-keys', body);
  }

  /**
   * `DELETE /api/translation-keys/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteTranslationKey(name: string): Observable<TranslationKeyDeleted> {
    return this._http.delete<TranslationKeyDeleted>(`/api/translation-keys/${encodeURIComponent(name)}`);
  }

  /**
   * `GET /api/translations/{code}/export`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  exportTranslations(code: string): Observable<TranslationBundle> {
    return this._http.get<TranslationBundle>(`/api/translations/${encodeURIComponent(code)}/export`);
  }

  /**
   * `GET /api/admin/translations`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getAdminTranslations(): Observable<TranslationAdminView> {
    return this._http.get<TranslationAdminView>('/api/admin/translations');
  }

  /**
   * `GET /api/translations/{code}`
   */
  getTranslations(code: string): Observable<TranslationBundleResponse> {
    return this._http.get<TranslationBundleResponse>(`/api/translations/${encodeURIComponent(code)}`);
  }

  /**
   * `PUT /api/translations/{code}/import`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  importTranslations(code: string, body: TranslationImportRequest): Observable<TranslationImportResult> {
    return this._http.put<TranslationImportResult>(`/api/translations/${encodeURIComponent(code)}/import`, body);
  }

  /**
   * `PUT /api/admin/translations`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  saveAdminTranslations(body: TranslationSaveRequest): Observable<TranslationSaveResult> {
    return this._http.put<TranslationSaveResult>('/api/admin/translations', body);
  }

  /**
   * `PUT /api/translation-keys/{name}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateTranslationKey(name: string, body: Partial<TranslationKeyPayload>): Observable<TranslationKey> {
    return this._http.put<TranslationKey>(`/api/translation-keys/${encodeURIComponent(name)}`, body);
  }
}
