// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { AdminUser, AdminUserDetail, ApiMessage, User, UserFilters } from '../models';
import { EnabledRequest, SetPasswordRequest, UserCreateRequest, UserQuery, UserUpdateRequest } from '../types';
import { toHttpParams } from '../http-params';

/**
 * The user list behind the admin site. Everything here needs a role.
 */
@Injectable({ providedIn: 'root' })
export class UserApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/users`
   *
   * Requires the `ADMIN` role.
   */
  createUser(body: UserCreateRequest): Observable<AdminUser> {
    return this._http.post<AdminUser>('/api/users', body);
  }

  /**
   * `DELETE /api/users/{id}`
   *
   * Requires the `ADMIN` role.
   */
  deleteUser(id: number): Observable<User> {
    return this._http.delete<User>(`/api/users/${id}`);
  }

  /**
   * `GET /api/users/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getUser(id: number): Observable<AdminUser> {
    return this._http.get<AdminUser>(`/api/users/${id}`);
  }

  /**
   * `GET /api/users/{id}/detail`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getUserDetail(id: number): Observable<AdminUserDetail> {
    return this._http.get<AdminUserDetail>(`/api/users/${id}/detail`);
  }

  /**
   * `GET /api/users/filters`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getUserFilters(): Observable<UserFilters> {
    return this._http.get<UserFilters>('/api/users/filters');
  }

  /**
   * `GET /api/users`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  getUsers(params?: UserQuery): Observable<AdminUser[]> {
    return this._http.get<AdminUser[]>('/api/users', { params: toHttpParams(params) });
  }

  /**
   * `PUT /api/users/{id}/enabled`
   *
   * Requires the `ADMIN` role.
   */
  setUserEnabled(id: number, body: EnabledRequest): Observable<AdminUser> {
    return this._http.put<AdminUser>(`/api/users/${id}/enabled`, body);
  }

  /**
   * `PUT /api/users/{id}/password`
   *
   * Requires the `ADMIN` role.
   */
  setUserPassword(id: number, body: SetPasswordRequest): Observable<ApiMessage> {
    return this._http.put<ApiMessage>(`/api/users/${id}/password`, body);
  }

  /**
   * `PUT /api/users/{id}`
   *
   * Requires the `ADMIN` role.
   */
  updateUser(id: number, body: UserUpdateRequest): Observable<AdminUser> {
    return this._http.put<AdminUser>(`/api/users/${id}`, body);
  }
}
