// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import {
  Weapon,
  WeaponAscension,
  WeaponAscensionCost,
  WeaponAscensionCostPayload,
  WeaponAscensionPayload,
  WeaponPayload,
  WeaponRefinement,
  WeaponRefinementPayload,
} from '../models';
import { ApiMessage, Expanded, WeaponFull } from '../types';

/**
 * Weapons, their refinements and their ascension costs.
 */
@Injectable({ providedIn: 'root' })
export class WeaponApiService {
  private readonly _http = inject(HttpClient);

  /**
   * `POST /api/weapons`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createWeapon(body: WeaponPayload): Observable<Expanded<Weapon, 'created_by'>> {
    return this._http.post<Expanded<Weapon, 'created_by'>>('/api/weapons', body);
  }

  /**
   * `POST /api/weapons-ascensions`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createWeaponAscension(body: WeaponAscensionPayload): Observable<Expanded<WeaponAscension, 'created_by'>> {
    return this._http.post<Expanded<WeaponAscension, 'created_by'>>('/api/weapons-ascensions', body);
  }

  /**
   * `POST /api/weapons-ascensions-cost`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createWeaponAscensionCost(body: WeaponAscensionCostPayload): Observable<Expanded<WeaponAscensionCost, 'created_by'>> {
    return this._http.post<Expanded<WeaponAscensionCost, 'created_by'>>('/api/weapons-ascensions-cost', body);
  }

  /**
   * `POST /api/weapons/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createWeaponFull(body: FormData): Observable<Weapon> {
    return this._http.post<Weapon>('/api/weapons/full', body);
  }

  /**
   * `POST /api/weapons-refinements`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  createWeaponRefinement(body: WeaponRefinementPayload): Observable<Expanded<WeaponRefinement, 'created_by'>> {
    return this._http.post<Expanded<WeaponRefinement, 'created_by'>>('/api/weapons-refinements', body);
  }

  /**
   * `DELETE /api/weapons/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteWeapon(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/weapons/${id}`);
  }

  /**
   * `DELETE /api/weapons-ascensions/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteWeaponAscension(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/weapons-ascensions/${id}`);
  }

  /**
   * `DELETE /api/weapons-ascensions-cost/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteWeaponAscensionCost(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/weapons-ascensions-cost/${id}`);
  }

  /**
   * `DELETE /api/weapons-refinements/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  deleteWeaponRefinement(id: number): Observable<ApiMessage> {
    return this._http.delete<ApiMessage>(`/api/weapons-refinements/${id}`);
  }

  /**
   * `GET /api/weapons/{id}`
   */
  getWeapon(id: number): Observable<Expanded<Weapon, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<Weapon, 'created_by' | 'updated_by'>>(`/api/weapons/${id}`);
  }

  /**
   * `GET /api/weapons-ascensions/{id}`
   */
  getWeaponAscension(id: number): Observable<Expanded<WeaponAscension, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<WeaponAscension, 'created_by' | 'updated_by'>>(`/api/weapons-ascensions/${id}`);
  }

  /**
   * `GET /api/weapons-ascensions-cost/{id}`
   */
  getWeaponAscensionCost(id: number): Observable<Expanded<WeaponAscensionCost, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<WeaponAscensionCost, 'created_by' | 'updated_by'>>(`/api/weapons-ascensions-cost/${id}`);
  }

  /**
   * `GET /api/weapons-ascensions-cost`
   */
  getWeaponAscensionCosts(): Observable<Expanded<WeaponAscensionCost, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<WeaponAscensionCost, 'created_by' | 'updated_by'>[]>('/api/weapons-ascensions-cost');
  }

  /**
   * `GET /api/weapons-ascensions`
   */
  getWeaponAscensions(): Observable<Expanded<WeaponAscension, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<WeaponAscension, 'created_by' | 'updated_by'>[]>('/api/weapons-ascensions');
  }

  /**
   * `GET /api/weapons/{id}/full`
   */
  getWeaponFull(id: number): Observable<WeaponFull> {
    return this._http.get<WeaponFull>(`/api/weapons/${id}/full`);
  }

  /**
   * `GET /api/weapons-refinements/{id}`
   */
  getWeaponRefinement(id: number): Observable<Expanded<WeaponRefinement, 'created_by' | 'updated_by'>> {
    return this._http.get<Expanded<WeaponRefinement, 'created_by' | 'updated_by'>>(`/api/weapons-refinements/${id}`);
  }

  /**
   * `GET /api/weapons-refinements`
   */
  getWeaponRefinements(): Observable<Expanded<WeaponRefinement, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<WeaponRefinement, 'created_by' | 'updated_by'>[]>('/api/weapons-refinements');
  }

  /**
   * `GET /api/weapons`
   */
  getWeapons(): Observable<Expanded<Weapon, 'created_by' | 'updated_by'>[]> {
    return this._http.get<Expanded<Weapon, 'created_by' | 'updated_by'>[]>('/api/weapons');
  }

  /**
   * `GET /api/weapons/full`
   */
  getWeaponsFull(): Observable<WeaponFull[]> {
    return this._http.get<WeaponFull[]>('/api/weapons/full');
  }

  /**
   * `PUT /api/weapons/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateWeapon(id: number, body: Partial<WeaponPayload>): Observable<Expanded<Weapon, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<Weapon, 'created_by' | 'updated_by'>>(`/api/weapons/${id}`, body);
  }

  /**
   * `PUT /api/weapons-ascensions/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateWeaponAscension(id: number, body: Partial<WeaponAscensionPayload>): Observable<Expanded<WeaponAscension, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<WeaponAscension, 'created_by' | 'updated_by'>>(`/api/weapons-ascensions/${id}`, body);
  }

  /**
   * `PUT /api/weapons-ascensions-cost/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateWeaponAscensionCost(id: number, body: Partial<WeaponAscensionCostPayload>): Observable<Expanded<WeaponAscensionCost, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<WeaponAscensionCost, 'created_by' | 'updated_by'>>(`/api/weapons-ascensions-cost/${id}`, body);
  }

  /**
   * `PUT /api/weapons/{id}/full`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateWeaponFull(id: number, body: FormData): Observable<Weapon> {
    return this._http.put<Weapon>(`/api/weapons/${id}/full`, body);
  }

  /**
   * `PUT /api/weapons-refinements/{id}`
   *
   * Requires the `ADMIN` or `EDITOR` role.
   */
  updateWeaponRefinement(id: number, body: Partial<WeaponRefinementPayload>): Observable<Expanded<WeaponRefinement, 'created_by' | 'updated_by'>> {
    return this._http.put<Expanded<WeaponRefinement, 'created_by' | 'updated_by'>>(`/api/weapons-refinements/${id}`, body);
  }
}
