// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { Saved } from '../types/common.type';

/**
 * A row of `artifacts` as the API reads it back.
 */
export interface Artifact {
  id: number;
  name: string;
  icon: string;
  icon_name: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  how_to_obtain_quality_1: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  how_to_obtain_quality_2: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  how_to_obtain_quality_3: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  how_to_obtain_quality_4: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  how_to_obtain_quality_5: string | null;
  version: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  effects: string | null;
  two_piece: string | null;
  four_piece: string | null;
  has_rarity_1: boolean;
  has_rarity_2: boolean;
  has_rarity_3: boolean;
  has_rarity_4: boolean;
  has_rarity_5: boolean;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `artifacts_pieces` as the API reads it back.
 */
export interface ArtifactPiece {
  id: number;
  artifact_id: number;
  icon: string;
  icon_name: string | null;
  type: string;
  name: string;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A body `Artifact` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface ArtifactPayload {
  name: string;
  icon: string;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  how_to_obtain_quality_1?: string[] | string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  how_to_obtain_quality_2?: string[] | string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  how_to_obtain_quality_3?: string[] | string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  how_to_obtain_quality_4?: string[] | string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  how_to_obtain_quality_5?: string[] | string | null;
  version?: string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  effects?: string[] | string | null;
  two_piece?: string | null;
  four_piece?: string | null;
  has_rarity_1?: boolean;
  has_rarity_2?: boolean;
  has_rarity_3?: boolean;
  has_rarity_4?: boolean;
  has_rarity_5?: boolean;
  icon_name?: string | null;
}

/**
 * A body `ArtifactPiece` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface ArtifactPiecePayload {
  artifact_id: number;
  icon: string;
  type: string;
  name: string;
  icon_name?: string | null;
}

/**
 * The shape of a `ArtifactFull` response.
 */
export interface ArtifactFull {
  artifact: Saved<ArtifactPayload>;
  pieces: Saved<ArtifactPiecePayload>[];
}

/**
 * The shape of a `ArtifactFullRow` response.
 */
export type ArtifactFullRow = Artifact & {
  pieces: Saved<ArtifactPiecePayload>[];
};
