// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `audit_logs` as the API reads it back.
 */
export interface AuditLog {
  id: number;
  table_name: string;
  record_id: string;
  action: 'INSERT' | 'UPDATE' | 'DELETE';
  changed_by: number | null;
  changed_at: string;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  changes: string | null;
}
