// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `audit_logs` as the API reads it back.
 */
export interface AuditLog {
  id: number;
  table_name: string;
  record_id: string;
  action: 'INSERT' | 'UPDATE' | 'DELETE' | 'RECONCILE' | 'MOVE';
  changed_by: number | null;
  changed_at: string;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  changes: string | null;
  entity_table: string | null;
  entity_id: string | null;
  session_id: number | null;
}

/**
 * One logged change.
 *
 * Two things differ from the `audit_logs` row: the username is joined in, and
 * `changes` is decoded - the column stores it as JSON text.
 */
export interface AuditLogEntry {
  id: number;
  table_name: string;
  record_id: string;
  /** What the changed row belongs to, which is the row itself unless it is a child - a talent's cost says `characters` and the character's id, so one filter gives the whole history of one thing. Null on entries written before the columns existed whose row has since been replaced. */
  entity_table: string | null;
  entity_id: string | null;
  /** INSERT | UPDATE | DELETE */
  action: string;
  changed_by: number | null;
  changed_by_username: string | null;
  /** The sign-in it was made from, which is what knows the address and the browser and can be revoked. Null for anything with no session behind it - a migration, a sweep, a file found on disk. */
  session_id: number | null;
  changed_at: string;
  /** Column to { old, new }. Absent on an insert, which logs the whole row. */
  changes: Record<string, unknown> | null;
}

/**
 * The shape of a `AuditLogFilters` response.
 */
export interface AuditLogFilters {
  tables: string[];
  actions: string[];
  users: AuditLogUser[];
}

/**
 * The shape of a `AuditLogPage` response.
 */
export interface AuditLogPage {
  total: number;
  page: number;
  pageSize: number;
  items: AuditLogEntry[];
}

/**
 * An account, reduced to what the audit filter needs to name it.
 */
export interface AuditLogUser {
  id: number;
  username: string;
}
