// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `users` as the API reads it back.
 */
export interface User {
  id: number;
  role: string;
  username: string;
  email: string;
  email_confirmed: boolean;
  password: string;
  background: string | null;
  language: string;
  deleted: boolean;
  theme_main: string;
  theme_admin: string;
  version: string | null;
  token: string | null;
  token_expires_at: string | null;
  created_at: string | null;
  updated_at: string | null;
}

/**
 * A bare acknowledgement. Most writes that return nothing else return this.
 */
export interface ApiMessage {
  message: string;
  /** Some endpoints add a sentence explaining what did *not* happen. */
  note?: string | null;
}

/**
 * The answer from the two endpoints that take an address and may send to it.
 *
 * Always the same, and says nothing about what was found. Whether there is an
 * account behind an address, whether it still needs confirming, whether it has
 * a password to reset - none of that is anything an endpoint open to the whole
 * internet should be willing to tell apart.
 */
export interface AuthMailRequested {
  requested: boolean;
}

/**
 * What registration hands back: no session, because there is not one yet.
 *
 * The account exists and cannot be used until the address on it is confirmed,
 * so the only useful things to say are which address the message went to and
 * whether it actually went. `sent` false is not an error - the account is made
 * either way - but it lets the page offer to try again instead of telling
 * somebody to go and look for a message that was never posted.
 */
export interface AuthPending {
  email: string;
  sent: boolean;
}

/**
 * Which ways in this deployment offers, asked before anybody has signed in.
 *
 * The client id is public by design - it travels in the page and identifies
 * the site to Google - so there is nothing here that the rendered button would
 * not give away anyway. Null, and `google_enabled` false, while no client id
 * is configured, which is how the site ships.
 */
export interface AuthProviders {
  google_enabled: boolean;
  google_client_id: string | null;
}

/**
 * What a successful register or login hands back.
 */
export interface AuthSession {
  /** The bearer token. Every later request carries it. */
  token: string;
  user: AuthUser;
}

/**
 * An account as the auth endpoints describe it. Never carries the password.
 */
export interface AuthUser {
  username: string;
  email: string;
  role: string;
  background: string | null;
  /** The site's own light/dark choice. */
  theme_main: string;
  /** The admin panel's, remembered separately. */
  theme_admin: string;
  language: string;
  email_confirmed: boolean;
  version: string | null;
  created_at: string;
  /** Whether there is a password on the account at all. */
  has_password: boolean;
  /** Whether it is still accepted. Distinct from having one: an account can keep its password and ask for it not to be a way in. */
  password_login_enabled: boolean;
  google_connected: boolean;
  /** The Google address that is connected, for the account page to show. */
  google_email: string | null;
}

/**
 * The shape of a `LanguageChanged` response.
 */
export interface LanguageChanged {
  language: string;
}

/**
 * Echoed back so the caller can confirm what was stored.
 */
export interface ThemeChanged {
  /** `main` or `admin`. */
  area: string;
  theme: string;
}
