// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { SessionEntry } from './user.model';

/**
 * A row of `users` as the API reads it back.
 */
export interface User {
  id: number;
  role: string;
  username: string;
  email: string;
  email_confirmed: boolean;
  password: string | null;
  background: string | null;
  language: string;
  deleted: boolean;
  version: string | null;
  created_at: string | null;
  updated_at: string | null;
  theme_main: string;
  theme_admin: string;
  password_login_enabled: boolean;
  totp_secret: string | null;
  totp_enabled: boolean;
  date_format: 'dmy_dot' | 'dmy_slash' | 'mdy_slash' | 'ymd_dash' | null;
  time_format: '24' | '12' | null;
  force_password_change: boolean;
}

/**
 * A bare acknowledgement. Most writes that return nothing else return this.
 */
export interface ApiMessage {
  message: string;
  /** Some endpoints add a sentence explaining what did *not* happen. */
  note?: string | null;
}

/**
 * The answer from the two endpoints that take an address and may send to it.
 *
 * Always the same, and says nothing about what was found. Whether there is an
 * account behind an address, whether it still needs confirming, whether it has
 * a password to reset - none of that is anything an endpoint open to the whole
 * internet should be willing to tell apart.
 */
export interface AuthMailRequested {
  requested: boolean;
}

/**
 * What registration hands back: no session, because there is not one yet.
 *
 * The account exists and cannot be used until the address on it is confirmed,
 * so the only useful things to say are which address the message went to and
 * whether it actually went. `sent` false is not an error - the account is made
 * either way - but it lets the page offer to try again instead of telling
 * somebody to go and look for a message that was never posted.
 */
export interface AuthPending {
  email: string;
  sent: boolean;
}

/**
 * Which ways in this deployment offers, asked before anybody has signed in.
 *
 * The client id is public by design - it travels in the page and identifies
 * the site to Google - so there is nothing here that the rendered button would
 * not give away anyway. Null, and `google_enabled` false, while no client id
 * is configured, which is how the site ships.
 */
export interface AuthProviders {
  google_enabled: boolean;
  google_client_id: string | null;
}

/**
 * What a successful register or login hands back.
 */
export interface AuthSession {
  /** The bearer token. Every later request carries it. */
  token: string;
  user: AuthUser;
  /** A secret for the browser to keep, when it asked to be remembered.  Present only where there was something to remember: an account with two-factor on, signing in with `remember_device`. Sent back on later sign-ins to skip the six digits - and nothing else, since the password still has to be right. Null every other time. */
  device_token: string | null;
}

/**
 * An account as the auth endpoints describe it. Never carries the password.
 */
export interface AuthUser {
  username: string;
  email: string;
  role: string;
  background: string | null;
  /** The site's own light/dark choice. */
  theme_main: string;
  /** The admin panel's, remembered separately. */
  theme_admin: string;
  language: string;
  /** How this reader wants dates written, or null for "as this device does". One of dmy_dot, dmy_slash, mdy_slash, ymd_dash. */
  date_format: string | null;
  /** '24', '12', or null for whatever the device says. */
  time_format: string | null;
  email_confirmed: boolean;
  version: string | null;
  created_at: string;
  /** Whether there is a password on the account at all. */
  has_password: boolean;
  /** Whether it is still accepted. Distinct from having one: an account can keep its password and ask for it not to be a way in. */
  password_login_enabled: boolean;
  google_connected: boolean;
  /** The Google address that is connected, for the account page to show. */
  google_email: string | null;
  /** Whether a code from an authenticator app is required to sign in. */
  totp_enabled: boolean;
  /** Unused recovery codes left. Zero when two-factor is off. */
  recovery_codes_remaining: number;
  /** Browsers that will not be asked for a code again. */
  trusted_devices: number;
  /** Whether the password on this account was chosen by somebody else.  Set when an admin makes the account by hand and asks for it. The site stops and asks for a new password before it will be used, and changing the password is what clears it. */
  force_password_change: boolean;
}

/**
 * The shape of a `LanguageChanged` response.
 */
export interface LanguageChanged {
  language: string;
}

/**
 * Every session this account has had, and how many attempts have failed since
 * it last succeeded.
 *
 * The count is deliberately "since the last good sign-in" rather than a
 * lifetime total: a number that only grows says nothing, and the question
 * worth answering is whether somebody has been trying lately.
 */
export interface SessionList {
  sessions: SessionEntry[];
  failed_since_last_login: number;
}

/**
 * How many sessions "sign out everywhere else" actually ended.
 */
export interface SessionsEnded {
  ended: number;
}

/**
 * Echoed back so the caller can confirm what was stored.
 */
export interface ThemeChanged {
  /** `main` or `admin`. */
  area: string;
  theme: string;
}

/**
 * The way back in when the phone is gone.
 *
 * Returned exactly once, when they are generated, because only their hashes
 * are kept. There is no endpoint that can show them again - asking for another
 * set replaces them.
 */
export interface TotpRecoveryCodes {
  recovery_codes: string[];
}

/**
 * A freshly issued two-factor secret, on its way to an authenticator app.
 *
 * Both forms of the same thing: the URI is what a QR code encodes, and the
 * secret is what somebody types when there is no camera to hand. Nothing is
 * required of the account until a code computed from it has been handed back.
 */
export interface TotpSetup {
  /** Base32, as an authenticator expects it typed. */
  secret: string;
  /** The otpauth:// URI a QR code carries. */
  uri: string;
}
