// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `backgrounds` as the API reads it back.
 */
export interface Background {
  id: number;
  name: string;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
  image_file_id: number | null;
  image: string | null;
  image_name: string | null;
  preview_file_id: number | null;
  preview: string | null;
  preview_name: string | null;
}

/**
 * A body `Background` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface BackgroundPayload {
  name: string;
  image_file_id?: number | null;
  image?: string | null;
  image_name?: string | null;
  preview_file_id?: number | null;
  preview?: string | null;
  preview_name?: string | null;
}
