// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * The shape of a `BackupDatabase` response.
 */
export interface BackupDatabase {
  alias: string;
  name: string;
  /** The dump on disk, e.g. `genshin_impact.dump`. */
  file: string | null;
  size: number | null;
  duration_ms: number | null;
  /** Counted before the dump, so the number describes what went into it. */
  rows: number;
  tables: BackupTableCount[] | null;
  error: string | null;
}

/**
 * The shape of a `BackupEntry` response.
 */
export interface BackupEntry {
  id: string;
  created_at: string;
  created_by: string | null;
  description: string | null;
  /** complete | partial | failed | incomplete */
  status: string;
  format: string | null;
  pg_dump_version: string | null;
  duration_ms: number | null;
  size: number;
  databases: BackupDatabase[];
  /** Only on a backup that never finished, explaining what it is. */
  note?: string | null;
}

/**
 * What restoring this database would cost, counted table by table.
 */
export interface BackupPreview {
  id: string;
  alias: string;
  name: string;
  created_at: string | null;
  live: BackupSize;
  backup: BackupSize;
  /** Rows that exist now, are absent from the backup, and would be lost. */
  lost: number;
  differences: RestoreDifference[];
}

/**
 * Rows and tables on one side of a restore.
 */
export interface BackupSize {
  rows: number;
  tables: number;
}

/**
 * Whether this installation can take a backup at all, and what it has already.
 */
export interface BackupStatus {
  driver: string | null;
  supported: boolean;
  pg_dump: string | null;
  pg_dump_version: string | null;
  pg_restore: string | null;
  directory: string;
  writable: boolean;
  free_space: number | null;
  backup_count: number;
  stored_size: number;
  databases: BackupStatusDatabase[];
}

/**
 * One database as the status page counts it, without reading any dump.
 */
export interface BackupStatusDatabase {
  alias: string;
  name: string;
  size: number | null;
  tables: number | null;
  error: string | null;
}

/**
 * What /api/backups answers with.
 *
 * None of this is in a database. A backup is a set of dump files with a
 * manifest beside them, so the manifest is the only place these shapes exist.
 */
export interface BackupTableCount {
  name: string;
  rows: number;
}

/**
 * The shape of a `RestoreDifference` response.
 */
export interface RestoreDifference {
  name: string;
  /** Null where the table is on one side only. */
  live: number | null;
  backup: number | null;
  /** Rows that exist now and are not in the backup, so the ones a restore loses. Meaningless for `kept`. */
  delta: number;
  /** `changed` - in both, with different counts. `created` - in the backup only, so the restore creates it. `kept`    - here only. pg_restore --clean drops what the dump contains, so a table made since the backup survives it. */
  kind: string;
}

/**
 * The shape of a `RestoreResult` response.
 */
export interface RestoreResult {
  restored: string;
  from: string;
  /** The backup taken of the old state immediately before replacing it. */
  safety_backup: string;
  duration_ms: number;
  disconnected: number;
  rows: number;
  tables: BackupTableCount[];
  warnings: string[];
}
