// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { Saved } from '../types/common.type';

/**
 * A row of `banners` as the API reads it back.
 */
export interface Banner {
  id: number;
  version: string;
  name: string;
  icon: string | null;
  icon_name: string | null;
  duration_from: string;
  duration_to: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `banners_characters` as the API reads it back.
 */
export interface BannerCharacter {
  id: number;
  banner_id: number;
  character_id: number;
  order: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `banners_weapons` as the API reads it back.
 */
export interface BannerWeapon {
  id: number;
  banner_id: number;
  weapon_id: number;
  order: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A body `Banner` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface BannerPayload {
  name: string;
  version: string;
  duration_from: string;
  duration_to?: string | null;
  icon?: string | null;
  icon_name?: string | null;
}

/**
 * A body `BannerCharacter` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface BannerCharacterPayload {
  banner_id: number;
  character_id: number;
  order: number;
}

/**
 * A body `BannerWeapon` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface BannerWeaponPayload {
  banner_id: number;
  weapon_id: number;
  order: number;
}

/**
 * The shape of a `BannerFull` response.
 */
export interface BannerFull {
  banner: Saved<BannerPayload>;
  characters: Saved<BannerCharacterPayload>[];
  weapons: Saved<BannerWeaponPayload>[];
}

/**
 * The shape of a `BannerFullRow` response.
 */
export type BannerFullRow = Banner & {
  characters: Saved<BannerCharacterPayload>[];
  weapons: Saved<BannerWeaponPayload>[];
};
