// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { Saved } from '../types/common.type';

/**
 * A row of `characters` as the API reads it back.
 */
export interface Character {
  id: number;
  name: string;
  element: string;
  weapon_type: string;
  rarity: number;
  title: string | null;
  secondary_title: string | null;
  region: string | null;
  model: string;
  birthday: string | null;
  special_dish: number | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  affiliations: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  how_to_obtain: string | null;
  is_traveler: boolean;
  namecard_description: string;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  namecard_sources: string | null;
  release_date: string | null;
  version: string;
  introduced: string | null;
  demo_music: string | null;
  voice_actor_english: string;
  voice_actor_japanese: string;
  voice_actor_korean: string;
  voice_actor_chinese: string;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
  icon_file_id: number | null;
  icon: string | null;
  icon_name: string | null;
  card_icon_file_id: number | null;
  card_icon: string | null;
  card_icon_name: string | null;
  card_icon_2_file_id: number | null;
  card_icon_2: string | null;
  card_icon_2_name: string | null;
  wish_icon_file_id: number | null;
  wish_icon: string | null;
  wish_icon_name: string | null;
  ingame_icon_file_id: number | null;
  ingame_icon: string | null;
  ingame_icon_name: string | null;
  ingame_icon_2_file_id: number | null;
  ingame_icon_2: string | null;
  ingame_icon_2_name: string | null;
  namecard_icon_file_id: number | null;
  namecard_icon: string | null;
  namecard_icon_name: string | null;
  namecard_background_file_id: number | null;
  namecard_background: string | null;
  namecard_background_name: string | null;
  namecard_banner_file_id: number | null;
  namecard_banner: string | null;
  namecard_banner_name: string | null;
}

/**
 * A row of `characters_ascensions` as the API reads it back.
 */
export interface CharacterAscension {
  id: number;
  character_id: number;
  character_id_2: number | null;
  character_id_3: number | null;
  character_id_4: number | null;
  character_id_5: number | null;
  character_id_6: number | null;
  character_id_7: number | null;
  phase: number;
  primary_stat: string;
  primary_stat_value: number;
  start_level_hp: number;
  start_level_atk: number;
  start_level_def: number;
  end_level_hp: number;
  end_level_atk: number;
  end_level_def: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_ascensions_cost` as the API reads it back.
 */
export interface CharacterAscensionCost {
  id: number;
  character_ascension_id: number;
  material_id: number;
  quantity: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
  order: number;
}

/**
 * A row of `characters_builds` as the API reads it back.
 */
export interface CharacterBuild {
  id: number;
  character_id: number;
  version: string;
  role: string;
  description: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_builds_artifacts` as the API reads it back.
 */
export interface CharacterBuildArtifact {
  id: number;
  character_build_id: number;
  artifact_id: number;
  pc_2: boolean;
  pc_4: boolean;
  order: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_builds_main_stats` as the API reads it back.
 */
export interface CharacterBuildMainStat {
  id: number;
  character_build_id: number;
  stat_name: string;
  artifact_type: string;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_builds_recommended_stats` as the API reads it back.
 */
export interface CharacterBuildRecommendedStat {
  id: number;
  character_build_id: number;
  stat_name: string;
  value_from: number;
  value_to: number | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_builds_sub_stats` as the API reads it back.
 */
export interface CharacterBuildSubStat {
  id: number;
  character_build_id: number;
  stat_name: string;
  recommended_value: string | null;
  order: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_builds_talents` as the API reads it back.
 */
export interface CharacterBuildTalent {
  id: number;
  character_build_id: number;
  talent_id: number;
  order: number;
  description: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_builds_teams` as the API reads it back.
 */
export interface CharacterBuildTeam {
  id: number;
  character_build_id: number;
  description: string | null;
  order: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_builds_teams_characters` as the API reads it back.
 */
export interface CharacterBuildTeamCharacter {
  id: number;
  character_build_team_id: number;
  character_id: number | null;
  order: number;
  element: string | null;
  flex: boolean;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_builds_weapons` as the API reads it back.
 */
export interface CharacterBuildWeapon {
  id: number;
  character_build_id: number;
  weapon_id: number;
  order: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_constellations` as the API reads it back.
 */
export interface CharacterConstellation {
  id: number;
  character_id: number;
  name: string;
  level: number;
  description: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
  icon_file_id: number | null;
  icon: string | null;
  icon_name: string | null;
}

/**
 * A row of `characters_relationships` as the API reads it back.
 */
export interface CharacterRelationship {
  id: number;
  character_id: number;
  type: string;
  name: string;
  state: string | null;
  is_biological: boolean;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_roles` as the API reads it back.
 */
export interface CharacterRole {
  id: number;
  character_id: number;
  role_name: string;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `characters_talents` as the API reads it back.
 */
export interface CharacterTalent {
  id: number;
  order: number;
  character_id: number;
  name: string;
  type: string;
  description: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
  icon_file_id: number | null;
  icon: string | null;
  icon_name: string | null;
}

/**
 * A row of `characters_talents_cost` as the API reads it back.
 */
export interface CharacterTalentCost {
  id: number;
  character_id: number;
  level: number;
  material_id: number;
  quantity: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
  order: number;
}

/**
 * A row of `characters_voice_overs` as the API reads it back.
 */
export interface CharacterVoiceOver {
  id: number;
  character_id: number;
  character_id_2: number | null;
  character_id_3: number | null;
  character_id_4: number | null;
  character_id_5: number | null;
  character_id_6: number | null;
  character_id_7: number | null;
  order: number;
  type: string;
  title_english: string;
  title_japanese: string | null;
  title_chinese: string | null;
  title_chinese_traditional: string | null;
  title_korean: string | null;
  text_english: string | null;
  text_japanese: string | null;
  text_chinese: string | null;
  text_chinese_traditional: string | null;
  text_korean: string | null;
  text_japanese_reading: string | null;
  text_chinese_reading: string | null;
  text_korean_reading: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
  audio_english_file_id: number | null;
  audio_english: string | null;
  audio_japanese_file_id: number | null;
  audio_japanese: string | null;
  audio_chinese_file_id: number | null;
  audio_chinese: string | null;
  audio_korean_file_id: number | null;
  audio_korean: string | null;
}

/**
 * A body `Character` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterPayload {
  name: string;
  element: string;
  weapon_type: string;
  rarity: number;
  model: string;
  namecard_description: string;
  version: string;
  voice_actor_english: string;
  voice_actor_japanese: string;
  voice_actor_korean: string;
  voice_actor_chinese: string;
  is_traveler?: boolean;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  how_to_obtain?: string[] | string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  affiliations?: string[] | string | null;
  namecard_icon_file_id?: number | null;
  namecard_icon?: string | null;
  namecard_icon_name?: string | null;
  namecard_background_file_id?: number | null;
  namecard_background?: string | null;
  namecard_background_name?: string | null;
  namecard_banner_file_id?: number | null;
  namecard_banner?: string | null;
  namecard_banner_name?: string | null;
  card_icon_file_id?: number | null;
  card_icon?: string | null;
  card_icon_name?: string | null;
  wish_icon_file_id?: number | null;
  wish_icon?: string | null;
  wish_icon_name?: string | null;
  ingame_icon_file_id?: number | null;
  ingame_icon?: string | null;
  ingame_icon_name?: string | null;
  icon_file_id?: number | null;
  icon?: string | null;
  icon_name?: string | null;
  card_icon_2_file_id?: number | null;
  card_icon_2?: string | null;
  card_icon_2_name?: string | null;
  ingame_icon_2_file_id?: number | null;
  ingame_icon_2?: string | null;
  ingame_icon_2_name?: string | null;
  title?: string | null;
  secondary_title?: string | null;
  region?: string | null;
  birthday?: string | null;
  special_dish?: number | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  namecard_sources?: string[] | string | null;
  release_date?: string | null;
  introduced?: string | null;
  demo_music?: string | null;
}

/**
 * A body `CharacterAscension` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterAscensionPayload {
  character_id: number;
  phase: number;
  primary_stat: string;
  primary_stat_value: number;
  start_level_hp: number;
  start_level_atk: number;
  start_level_def: number;
  end_level_hp: number;
  end_level_atk: number;
  end_level_def: number;
  character_id_2?: number | null;
  character_id_3?: number | null;
  character_id_4?: number | null;
  character_id_5?: number | null;
  character_id_6?: number | null;
  character_id_7?: number | null;
}

/**
 * A body `CharacterAscensionCost` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterAscensionCostPayload {
  character_ascension_id: number;
  material_id: number;
  order: number;
  quantity: number;
}

/**
 * A body `CharacterBuild` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterBuildPayload {
  character_id: number;
  version: string;
  role: string;
  description?: string | null;
}

/**
 * A body `CharacterBuildArtifact` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterBuildArtifactPayload {
  character_build_id: number;
  artifact_id: number;
  order: number;
  pc_2?: boolean;
  pc_4?: boolean;
}

/**
 * A body `CharacterBuildMainStat` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterBuildMainStatPayload {
  character_build_id: number;
  stat_name: string;
  artifact_type: string;
}

/**
 * A body `CharacterBuildRecommendedStat` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterBuildRecommendedStatPayload {
  character_build_id: number;
  stat_name: string;
  value_from: number;
  value_to?: number | null;
}

/**
 * A body `CharacterBuildSubStat` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterBuildSubStatPayload {
  character_build_id: number;
  stat_name: string;
  order: number;
  recommended_value?: string | null;
}

/**
 * A body `CharacterBuildTalent` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterBuildTalentPayload {
  character_build_id: number;
  talent_id: number;
  order: number;
  description?: string | null;
}

/**
 * A body `CharacterBuildTeam` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterBuildTeamPayload {
  character_build_id: number;
  order: number;
  description?: string | null;
}

/**
 * A body `CharacterBuildTeamCharacter` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterBuildTeamCharacterPayload {
  character_build_team_id: number;
  order: number;
  character_id?: number | null;
  element?: string | null;
  flex?: boolean;
}

/**
 * A body `CharacterBuildWeapon` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterBuildWeaponPayload {
  character_build_id: number;
  weapon_id: number;
  order: number;
}

/**
 * A body `CharacterConstellation` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterConstellationPayload {
  character_id: number;
  name: string;
  level: number;
  icon_file_id?: number | null;
  icon?: string | null;
  icon_name?: string | null;
  description?: string | null;
}

/**
 * A body `CharacterRelationship` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterRelationshipPayload {
  character_id: number;
  type: string;
  name: string;
  state: string;
  is_biological?: boolean;
}

/**
 * A body `CharacterRole` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterRolePayload {
  character_id: number;
  role_name: string;
}

/**
 * A body `CharacterTalent` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterTalentPayload {
  character_id: number;
  order: number;
  name: string;
  type: string;
  icon_file_id?: number | null;
  icon?: string | null;
  icon_name?: string | null;
  description?: string | null;
}

/**
 * A body `CharacterTalentCost` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterTalentCostPayload {
  character_id: number;
  order: number;
  level: number;
  material_id: number;
  quantity: number;
}

/**
 * A body `CharacterVoiceOver` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface CharacterVoiceOverPayload {
  character_id: number;
  order: number;
  type: string;
  title_english: string;
  text_english?: string | null;
  title_japanese?: string | null;
  title_chinese?: string | null;
  title_chinese_traditional?: string | null;
  title_korean?: string | null;
  text_japanese?: string | null;
  text_chinese?: string | null;
  text_chinese_traditional?: string | null;
  text_korean?: string | null;
  character_id_2?: number | null;
  character_id_3?: number | null;
  character_id_4?: number | null;
  character_id_5?: number | null;
  character_id_6?: number | null;
  character_id_7?: number | null;
  text_japanese_reading?: string | null;
  text_chinese_reading?: string | null;
  text_korean_reading?: string | null;
  audio_english_file_id?: number | null;
  audio_english?: string | null;
  audio_japanese_file_id?: number | null;
  audio_japanese?: string | null;
  audio_chinese_file_id?: number | null;
  audio_chinese?: string | null;
  audio_korean_file_id?: number | null;
  audio_korean?: string | null;
}

/**
 * `GET /api/characters/{id}/full`
 *
 * The odd one out: characters predate registerFullResource(), so their costs
 * come back flat rather than nested under the phase or level they belong to.
 * The write side nests ascension costs and spells the talent costs
 * `talent_costs`, which is why the form rebuilds the body rather than putting
 * back what it was given.
 */
export interface CharacterFull {
  character: Saved<CharacterPayload>;
  voice_overs: Saved<CharacterVoiceOverPayload>[];
  constellations: Saved<CharacterConstellationPayload>[];
  ascensions: Saved<CharacterAscensionPayload>[];
  ascension_cost: Saved<CharacterAscensionCostPayload>[];
  talents: Saved<CharacterTalentPayload>[];
  talent_cost: Saved<CharacterTalentCostPayload>[];
  relationships: Saved<CharacterRelationshipPayload>[];
  roles: string[];
}
