// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { AssetConversionCount, AssetFormatCount } from './file.model';

/**
 * A row of `feedback` as the API reads it back.
 */
export interface Feedback {
  id: number;
  type: 'Bug' | 'Suggestion' | 'Other';
  status: 'new' | 'read' | 'resolved' | 'spam';
  section: string | null;
  title: string | null;
  user_id: number | null;
  username: string | null;
  email: string | null;
  message: string | null;
  steps_to_reproduce: string | null;
  expected_behavior: string | null;
  actual_behavior: string | null;
  browser_device_info: string | null;
  details: string | null;
  why_important: string | null;
  additional_info: string | null;
  page_url: string | null;
  user_agent: string | null;
  language: string | null;
  submitter_hash: string | null;
  created_at: string | null;
  updated_at: string | null;
}

/**
 * The shape of a `DashboardActivity` response.
 */
export interface DashboardActivity {
  today: number;
  last7: number;
  last30: number;
  recent: DashboardChange[];
}

/**
 * The asset tree in three numbers and a short list.
 *
 * The same survey the Files page draws in full, cut down to what a card holds:
 * how much there is, and how much of it has no converted twin. Cached for a
 * day, so `age` is how old the answer is rather than how long it took.
 */
export interface DashboardAssets {
  total_files: number;
  total_bytes: number;
  /** Every extension in the tree, biggest first. */
  formats: AssetFormatCount[];
  images: AssetConversionCount;
  audio: AssetConversionCount;
  generated_at: string;
  age: number;
}

/**
 * The shape of a `DashboardChange` response.
 */
export interface DashboardChange {
  id: number;
  table_name: string;
  record_id: string;
  action: string;
  changed_at: string;
  changed_by_username: string | null;
}

/**
 * One row of the content counts, and where to go to edit it.
 */
export interface DashboardContent {
  label: string;
  table: string;
  route: string;
  icon: string;
  total: number;
}

/**
 * The shape of a `DashboardFeedback` response.
 */
export interface DashboardFeedback {
  total: number;
  new: number;
  last7: number;
  last30: number;
  byType: DashboardFeedbackType[];
}

/**
 * The shape of a `DashboardFeedbackType` response.
 */
export interface DashboardFeedbackType {
  type: string;
  total: number;
}

/**
 * Records missing something they ought to have.
 */
export interface DashboardGap {
  label: string;
  route: string;
  missing: number;
  total: number;
}

/**
 * The shape of a `DashboardLanguage` response.
 */
export interface DashboardLanguage {
  code: string;
  name: string;
  native_name: string;
  enabled: boolean;
  translated: number;
}

/**
 * The shape of a `DashboardStats` response.
 */
export interface DashboardStats {
  content: DashboardContent[];
  /** Biggest job first. */
  gaps: DashboardGap[];
  feedback: DashboardFeedback;
  activity: DashboardActivity;
  translations: DashboardTranslations;
  assets: DashboardAssets;
}

/**
 * The shape of a `DashboardTranslations` response.
 */
export interface DashboardTranslations {
  keys: number;
  languages: DashboardLanguage[];
}
