// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `feedback` as the API reads it back.
 */
export interface Feedback {
  id: number;
  type: 'Bug' | 'Suggestion' | 'Other';
  status: 'new' | 'read' | 'resolved' | 'spam';
  section: string | null;
  title: string | null;
  user_id: number | null;
  username: string | null;
  email: string | null;
  message: string | null;
  steps_to_reproduce: string | null;
  expected_behavior: string | null;
  actual_behavior: string | null;
  browser_device_info: string | null;
  details: string | null;
  why_important: string | null;
  additional_info: string | null;
  page_url: string | null;
  user_agent: string | null;
  language: string | null;
  submitter_hash: string | null;
  created_at: string | null;
  updated_at: string | null;
}
