// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `enemies` as the API reads it back.
 */
export interface Enemy {
  id: number;
  name: string;
  icon: string;
  icon_name: string | null;
  description: string | null;
  version: string | null;
  interactive_map_link: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `enemies_damage_types_elements` as the API reads it back.
 */
export interface EnemyDamageTypeElement {
  id: number;
  enemy_phase_id: number;
  damage_type_element: string;
  order: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `enemies_drops` as the API reads it back.
 */
export interface EnemyDrop {
  id: number;
  enemy_id: number;
  material_id: number | null;
  artifact_id: number | null;
  level_from: number | null;
  level_to: number | null;
  domain_level: string | null;
  world_level: number | null;
  quantity_from: number | null;
  quantity_to: number | null;
  drop_rate: number | null;
  average: number | null;
  rarity: number | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `enemies_phases` as the API reads it back.
 */
export interface EnemyPhase {
  id: number;
  enemy_id: number;
  title: string;
  secondary_title: string | null;
  icon: string;
  icon_name: string | null;
  art: string | null;
  art_name: string | null;
  has_weakpoint: boolean | null;
  living_being_type: string | null;
  living_being_family: string | null;
  living_being_group: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A body `Enemy` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface EnemyPayload {
  name: string;
  icon: string;
  version?: string | null;
  description?: string | null;
  interactive_map_link?: string | null;
  icon_name?: string | null;
}

/**
 * A body `EnemyDamageTypeElement` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface EnemyDamageTypeElementPayload {
  enemy_phase_id: number;
  damage_type_element: string;
  order: number;
}

/**
 * A body `EnemyDrop` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface EnemyDropPayload {
  enemy_id: number;
  material_id?: number | null;
  artifact_id?: number | null;
  level_from?: number | null;
  level_to?: number | null;
  domain_level?: string | null;
  world_level?: number | null;
  quantity_from?: number | null;
  quantity_to?: number | null;
  drop_rate?: number | null;
  average?: number | null;
  rarity?: number | null;
}

/**
 * A body `EnemyPhase` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface EnemyPhasePayload {
  enemy_id: number;
  title: string;
  icon: string;
  living_being_type?: string | null;
  living_being_family?: string | null;
  living_being_group?: string | null;
  secondary_title?: string | null;
  art?: string | null;
  has_weakpoint?: boolean | null;
  icon_name?: string | null;
  art_name?: string | null;
}
