// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { Feedback } from './dashboard.model';

/**
 * The shape of a `FeedbackFilters` response.
 */
export interface FeedbackFilters {
  sections: string[];
  statuses: string[];
  types: string[];
  byStatus: Record<string, number>;
  byType: Record<string, number>;
}

/**
 * The shape of a `FeedbackPage` response.
 */
export interface FeedbackPage {
  total: number;
  page: number;
  pageSize: number;
  items: Feedback[];
}

/**
 * Echoed back after a status change, so the list can update in place.
 */
export interface FeedbackStatusChanged {
  id: number;
  status: string;
}
