// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * The shape of a `AssetFile` response.
 */
export interface AssetFile {
  name: string;
  extension: string;
  size: number;
  modified: string;
  /** The path the site loads it by, e.g. `assets/materials/Foo.avif`. */
  url: string;
}

/**
 * The shape of a `AssetFilePage` response.
 */
export interface AssetFilePage {
  folder: string;
  total: number;
  page: number;
  pageSize: number;
  files: AssetFile[];
}

/**
 * What /api/files and the upload endpoints answer with.
 *
 * None of this is in a database. The files on disk are the record, and these
 * endpoints walk the folder rather than a table.
 */
export interface AssetFolder {
  folder: string;
  files: number;
}

/**
 * The shape of a `AssetRestoreResult` response.
 */
export interface AssetRestoreResult {
  folder: string;
  name: string;
}

/**
 * Deleting moves the file to the trash under a stamped name; nothing is lost.
 */
export interface AssetTrashResult {
  folder: string;
  name: string;
  trashed: string;
}

/**
 * The shape of a `AssetUploadResult` response.
 */
export interface AssetUploadResult {
  folder: string;
  path: string;
  /** Same as `path`, relative to the site root. */
  url: string;
}

/**
 * `POST /api/uploads/{entity}/{field}` - stored where that field's files go,
 * but written onto no row. Used while a form is still being filled in.
 */
export interface EntityUploadResult {
  entity: string;
  field: string;
  /** The base name it was stored under: no folder, no extension. */
  name: string;
  path: string;
}

/**
 * `POST /api/uploads/{entity}/{id}/{field}` - the same, and the resulting path
 * written back onto the row.
 */
export interface RecordUploadResult {
  entity: string;
  id: number;
  field: string;
  name: string;
  /** The column the base name went into, or null where there is none. */
  nameColumn: string | null;
  path: string;
}

/**
 * The shape of a `TrashedFile` response.
 */
export interface TrashedFile {
  folder: string;
  /** The stamped name on disk, which is what restores it. */
  trashed: string;
  name: string;
  deleted_at: string;
  size: number;
}

/**
 * `POST /api/upload` - a file dropped into a folder, with nothing else touched.
 */
export interface UploadResult {
  filename: string;
  path: string;
}
