// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A kind of asset, and where that kind lives.
 *
 * `path` is the folder under `assets/`, and it is what a file's own path is
 * built from - so changing it moves files. `is_system` marks the one category
 * nothing may rename or remove, because every file with no category needs
 * somewhere to be.
 */
export interface FileCategory {
  id: number;
  /** Dotted, the way the front end names asset folders: `character.icon`. */
  code: string;
  label: string;
  path: string;
  /** Retired rather than removed, so it can come back with its history. */
  deleted: boolean;
  is_system: boolean;
  sort_order: number;
  files: number;
  bytes: number;
}
