// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * The shape of a `AssetBlockedCount` response.
 */
export interface AssetBlockedCount {
  images: number;
  audio: number;
}

/**
 * One medium's conversion health.
 *
 * `missing` is work an encoder can do. `converted_only` is not: a PNG decoded
 * back out of an AVIF is a bigger copy of the lossy one, not the original, so
 * those are reported and left alone.
 */
export interface AssetConversionCount {
  /** Groups holding a source this medium can be converted from. */
  sources: number;
  missing: number;
  converted_only: number;
  /** False when nothing on this box can write the target format. */
  can_convert: boolean;
}

/**
 * How far the conversion has got.
 *
 * The work is a queue on disk worked through a batch per request, so this is
 * both the answer to "convert some more" and to "where are we".
 */
export interface AssetConvertProgress {
  started_at: string;
  total: number;
  converted: number;
  failed: number;
  /** Already there, or gone, by the time its turn came. */
  skipped: number;
  remaining: number;
  finished: boolean;
  /** Left out of the queue because this box cannot write that format. */
  blocked: AssetBlockedCount;
  /** The first few that would not convert, to see a pattern by. */
  failures: string[];
}

/**
 * The shape of a `AssetFile` response.
 */
export interface AssetFile {
  name: string;
  extension: string;
  size: number;
  modified: string;
  /** The path the site loads it by, e.g. `assets/materials/Foo.avif`. */
  url: string;
}

/**
 * The shape of a `AssetFilePage` response.
 */
export interface AssetFilePage {
  folder: string;
  total: number;
  page: number;
  pageSize: number;
  files: AssetFile[];
}

/**
 * What /api/files and the upload endpoints answer with.
 *
 * None of this is in a database. The files on disk are the record, and these
 * endpoints walk the folder rather than a table.
 */
export interface AssetFolder {
  folder: string;
  files: number;
}

/**
 * The shape of a `AssetFormatCount` response.
 */
export interface AssetFormatCount {
  /** Lower case, with no dot. `(none)` for a file with no extension. */
  extension: string;
  files: number;
  bytes: number;
}

/**
 * The shape of a `AssetRestoreResult` response.
 */
export interface AssetRestoreResult {
  folder: string;
  name: string;
}

/**
 * The shape of a `AssetStats` response.
 */
export interface AssetStats {
  generated_at: string;
  /** Seconds since the survey was walked, so the page can say how stale it is. */
  age: number;
  total_files: number;
  total_bytes: number;
  formats: AssetFormatCount[];
  images: AssetConversionCount;
  audio: AssetConversionCount;
}

/**
 * Deleting moves the file to the trash under a stamped name; nothing is lost.
 */
export interface AssetTrashResult {
  folder: string;
  name: string;
  trashed: string;
}

/**
 * The shape of a `AssetUploadResult` response.
 */
export interface AssetUploadResult {
  folder: string;
  path: string;
  /** Same as `path`, relative to the site root. */
  url: string;
}

/**
 * `POST /api/uploads/{entity}/{field}` - stored where that field's files go,
 * but written onto no row. Used while a form is still being filled in.
 */
export interface EntityUploadResult {
  entity: string;
  field: string;
  /** The base name it was stored under: no folder, no extension. */
  name: string;
  path: string;
}

/**
 * `POST /api/uploads/{entity}/{id}/{field}` - the same, and the resulting path
 * written back onto the row.
 */
export interface RecordUploadResult {
  entity: string;
  id: number;
  field: string;
  name: string;
  /** The column the base name went into, or null where there is none. */
  nameColumn: string | null;
  path: string;
}

/**
 * The shape of a `TrashedFile` response.
 */
export interface TrashedFile {
  folder: string;
  /** The stamped name on disk, which is what restores it. */
  trashed: string;
  name: string;
  deleted_at: string;
  size: number;
}

/**
 * `POST /api/upload` - a file dropped into a folder, with nothing else touched.
 */
export interface UploadResult {
  filename: string;
  path: string;
}
