// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { Saved } from '../types/common.type';

/**
 * A row of `foods` as the API reads it back.
 */
export interface Food {
  id: number;
  name: string;
  description_normal: string | null;
  description_delicious: string | null;
  description_suspicious: string | null;
  effect: string | null;
  type: string | null;
  rarity: number | null;
  proficiency: number | null;
  base_dish_id: number | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  events: string | null;
  region: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  how_to_obtain: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  effects: string | null;
  effect_normal: string | null;
  effect_delicious: string | null;
  effect_suspicious: string | null;
  version: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
  icon_normal_file_id: number | null;
  icon_normal: string | null;
  icon_normal_name: string | null;
  icon_delicious_file_id: number | null;
  icon_delicious: string | null;
  icon_delicious_name: string | null;
  icon_suspicious_file_id: number | null;
  icon_suspicious: string | null;
  icon_suspicious_name: string | null;
}

/**
 * A row of `foods_recipe` as the API reads it back.
 */
export interface FoodRecipe {
  id: number;
  food_id: number;
  material_id: number;
  quantity: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A body `Food` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface FoodPayload {
  name: string;
  icon_normal_file_id?: number | null;
  icon_normal?: string | null;
  icon_normal_name?: string | null;
  icon_delicious_file_id?: number | null;
  icon_delicious?: string | null;
  icon_delicious_name?: string | null;
  icon_suspicious_file_id?: number | null;
  icon_suspicious?: string | null;
  icon_suspicious_name?: string | null;
  rarity?: number | null;
  proficiency?: number | null;
  description_normal?: string | null;
  description_delicious?: string | null;
  description_suspicious?: string | null;
  effect?: string | null;
  effect_normal?: string | null;
  effect_delicious?: string | null;
  effect_suspicious?: string | null;
  type?: string | null;
  base_dish_id?: number | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  events?: string[] | string | null;
  region?: string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  how_to_obtain?: string[] | string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  effects?: string[] | string | null;
  version?: string | null;
}

/**
 * A body `FoodRecipe` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface FoodRecipePayload {
  food_id: number;
  material_id: number;
  quantity: number;
}

/**
 * The shape of a `FoodFull` response.
 */
export interface FoodFull {
  food: Saved<FoodPayload>;
  recipe: Saved<FoodRecipePayload>[];
}

/**
 * The shape of a `FoodFullRow` response.
 */
export type FoodFullRow = Food & {
  recipe: Saved<FoodRecipePayload>[];
};
