// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

export * from './artifact.model';
export * from './audit-log.model';
export * from './auth.model';
export * from './background.model';
export * from './backup.model';
export * from './banner.model';
export * from './character.model';
export * from './dashboard.model';
export * from './enemy.model';
export * from './feedback.model';
export * from './file.model';
export * from './food.model';
export * from './language.model';
export * from './lookup.model';
export * from './material.model';
export * from './migration.model';
export * from './quiz.model';
export * from './stat.model';
export * from './translation.model';
export * from './user.model';
export * from './weapon.model';
