// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A body `User\Language` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface LanguagePayload {
  code: string;
  name: string;
  native_name: string;
  enabled?: boolean | null;
  sort_order?: number | null;
}
