// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { User } from './auth.model';

/**
 * A row of `artifact_piece_types` as the API reads it back.
 */
export interface ArtifactPieceType {
  name: string;
}

/**
 * A row of `character_models` as the API reads it back.
 */
export interface CharacterModel {
  name: string;
}

/**
 * A row of `character_states` as the API reads it back.
 */
export interface CharacterState {
  name: string;
}

/**
 * A row of `domain_levels` as the API reads it back.
 */
export interface DomainLevel {
  name: string;
}

/**
 * A row of `elements` as the API reads it back.
 */
export interface Element {
  name: string;
  icon_file_id: number | null;
  icon: string | null;
  icon_name: string | null;
}

/**
 * A row of `enemy_families` as the API reads it back.
 */
export interface EnemyFamily {
  name: string;
}

/**
 * A row of `enemy_groups` as the API reads it back.
 */
export interface EnemyGroup {
  name: string;
}

/**
 * A row of `enemy_types` as the API reads it back.
 */
export interface EnemyType {
  name: string;
}

/**
 * A row of `food_types` as the API reads it back.
 */
export interface FoodType {
  name: string;
}

/**
 * A row of `material_groups` as the API reads it back.
 */
export interface MaterialGroup {
  name: string;
}

/**
 * A row of `material_types` as the API reads it back.
 */
export interface MaterialType {
  name: string;
}

/**
 * A row of `rarities` as the API reads it back.
 */
export interface Rarity {
  name: number;
}

/**
 * A row of `regions` as the API reads it back.
 */
export interface Region {
  name: string;
  icon_file_id: number | null;
  icon: string | null;
  icon_name: string | null;
}

/**
 * A row of `relationship_types` as the API reads it back.
 */
export interface RelationshipType {
  name: string;
}

/**
 * A row of `roles` as the API reads it back.
 */
export interface Role {
  name: string;
}

/**
 * A row of `talent_types` as the API reads it back.
 */
export interface TalentType {
  name: string;
}

/**
 * A row of `voice_over_types` as the API reads it back.
 */
export interface VoiceOverType {
  name: string;
}

/**
 * A row of `weapon_types` as the API reads it back.
 */
export interface WeaponType {
  name: string;
  icon_file_id: number | null;
  icon: string | null;
  icon_name: string | null;
}

/**
 * A body `DomainLevel` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface DomainLevelPayload {
  name: string;
}

/**
 * A body `EnemyFamily` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface EnemyFamilyPayload {
  name: string;
}

/**
 * A body `EnemyGroup` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface EnemyGroupPayload {
  name: string;
}

/**
 * A body `EnemyType` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface EnemyTypePayload {
  name: string;
}

/**
 * A body `FoodType` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface FoodTypePayload {
  name: string;
}

/**
 * A body `MaterialGroup` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface MaterialGroupPayload {
  name: string;
}

/**
 * A body `MaterialType` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface MaterialTypePayload {
  name: string;
}

/**
 * A body `Region` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface RegionPayload {
  name: string;
}

/**
 * A body `RelationshipType` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface RelationshipTypePayload {
  name: string;
}

/**
 * A body `TalentType` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface TalentTypePayload {
  name: string;
}

/**
 * A body `User\Role` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface RolePayload {
  name: string;
}

/**
 * How many log files were removed.
 */
export interface ErrorLogCleared {
  deleted: number;
}

/**
 * One thing that went wrong.
 *
 * Read back from the JSON lines under php/storage/logs rather than a table, so
 * that an outage of the database is a thing this can report rather than a thing
 * that stops it reporting.
 */
export interface ErrorLogEntry {
  at: string;
  /** error | warning */
  level: string;
  status: number;
  /** The exception class, or `Response` when a handler answered 5xx without throwing. */
  type: string;
  message: string;
  file: string;
  line: number;
  method: string;
  path: string;
  user_id: number | null;
  session_id: number | null;
  ip: string | null;
  /** Identity of the failure, shared by every repeat of it. */
  fingerprint: string;
  trace: string | null;
}

/**
 * Every occurrence of one failure, collapsed into a row with a count beside it.
 */
export interface ErrorLogGroup {
  fingerprint: string;
  level: string;
  status: number;
  type: string;
  message: string;
  file: string;
  line: number;
  count: number;
  first_at: string;
  last_at: string;
  /** The paths this failure was reached through, most-hit first. */
  paths: string[];
  /** The most recent occurrence, in full. */
  latest: ErrorLogEntry;
}

/**
 * What the error log has to say, ready to draw.
 */
export interface ErrorLogReport {
  /** Matching the filter, before the limit. */
  total: number;
  errors: number;
  warnings: number;
  /** Distinct failures, which is usually far fewer than `total`. */
  distinct: number;
  /** Every day a log file exists for, newest first. */
  days: string[];
  /** one per day in range, oldest first, for the chart */
  daily: ErrorLogTally[];
  /** one per status code seen */
  statuses: ErrorLogTally[];
  groups: ErrorLogGroup[];
}

/**
 * How many of something. Used for the counts by status and by day.
 */
export interface ErrorLogTally {
  key: string;
  errors: number;
  warnings: number;
}
