// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `materials` as the API reads it back.
 */
export interface Material {
  id: number;
  name: string;
  icon: string | null;
  icon_name: string | null;
  type: string | null;
  group: string | null;
  region: string | null;
  rarity: number | null;
  description: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  how_to_obtain: string | null;
  version: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `materials_groups_join` as the API reads it back.
 */
export interface MaterialGroupJoin {
  id: number;
  material_id: number;
  group: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A body `Material` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface MaterialPayload {
  name: string;
  type?: string | null;
  group?: string | null;
  region?: string | null;
  description?: string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  how_to_obtain?: string[] | string | null;
  version?: string | null;
  rarity?: number | null;
  icon?: string | null;
  icon_name?: string | null;
}

/**
 * A body `MaterialGroupJoin` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface MaterialGroupJoinPayload {
  material_id: number;
  group?: string | null;
}
