// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `migrations` as the API reads it back.
 */
export interface Migration {
  id: number;
  filename: string;
  applied_at: string | null;
}
