// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `quiz_stats_history` as the API reads it back.
 */
export interface QuizStatsHistory {
  user_id: number;
  character_id: number;
  quiz_id: number;
  wins: number;
  losses: number;
  attempts: number;
  created_at: string | null;
  updated_at: string | null;
}

/**
 * A row of `quizzes` as the API reads it back.
 */
export interface Quiz {
  id: number;
  name: string;
  deleted: boolean;
  created_at: string | null;
}

/**
 * A row of `quizzes_states` as the API reads it back.
 */
export interface QuizState {
  user_id: number;
  quiz_id: number;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  state: string | null;
  is_daily: boolean;
  created_at: string | null;
  updated_at: string | null;
}

/**
 * A row of `user_quiz_history` as the API reads it back.
 */
export interface QuizHistory {
  id: number;
  user_id: number;
  character_id: number;
  quiz_id: number;
  win: boolean;
  attempts: number;
  difficulty: number | null;
  created_at: string | null;
}

/**
 * A body `Quiz` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface QuizPayload {
  name: string;
}

/**
 * A body `QuizState` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface QuizStatePayload {
  user_id: number;
  quiz_id: number;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  state?: string[] | string | null;
  is_daily?: boolean | null;
}

/**
 * A body `QuizStatsHistory` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface QuizStatsHistoryPayload {
  user_id: number;
  character_id: number;
  quiz_id: number;
  wins: number;
  losses: number;
  attempts?: number;
}

/**
 * A body `UserQuizHistory` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface UserQuizHistoryPayload {
  user_id: number;
  character_id: number;
  quiz_id: number;
  win: boolean;
  attempts?: number;
  difficulty?: number | null;
}
