// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `quiz_stats_history` as the API reads it back.
 */
export interface QuizStatsHistory {
  user_id: number;
  character_id: number;
  quiz_id: number;
  wins: number;
  losses: number;
  attempts: number;
  created_at: string | null;
  updated_at: string | null;
}

/**
 * A row of `quizzes` as the API reads it back.
 */
export interface Quiz {
  id: number;
  name: string;
  deleted: boolean;
  created_at: string | null;
}

/**
 * A row of `quizzes_states` as the API reads it back.
 */
export interface QuizState {
  user_id: number;
  quiz_id: number;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  state: string | null;
  is_daily: boolean;
  created_at: string | null;
  updated_at: string | null;
}

/**
 * A row of `user_quiz_history` as the API reads it back.
 */
export interface QuizHistory {
  id: number;
  user_id: number;
  character_id: number;
  quiz_id: number;
  win: boolean;
  attempts: number;
  difficulty: number | null;
  created_at: string | null;
}

/**
 * A body `Quiz` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface QuizPayload {
  name: string;
}

/**
 * A body `QuizState` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface QuizStatePayload {
  user_id: number;
  quiz_id: number;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  state?: string[] | string | null;
  is_daily?: boolean | null;
}

/**
 * A body `QuizStatsHistory` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface QuizStatsHistoryPayload {
  user_id: number;
  character_id: number;
  quiz_id: number;
  wins: number;
  losses: number;
  attempts?: number;
}

/**
 * A body `UserQuizHistory` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface UserQuizHistoryPayload {
  user_id: number;
  character_id: number;
  quiz_id: number;
  win: boolean;
  attempts?: number;
  difficulty?: number | null;
}

/**
 * What the quiz endpoints answer with.
 *
 * A saved game's `state` is deliberately opaque: it is the front end's own
 * shape, stored as it arrives. What is in it is the browser's business; only
 * who it belongs to is the server's.
 */
export interface QuizProgress {
  /** The quiz's name, which is what the URL uses. */
  quiz: string;
  /** The front end's own shape, stored as it arrives and handed back untouched. Nothing on this side reads into it. */
  state: Record<string, unknown>;
  is_daily: boolean;
}

/**
 * The shape of a `QuizProgressDeleted` response.
 */
export interface QuizProgressDeleted {
  deleted: number;
}

/**
 * The shape of a `QuizProgressSaved` response.
 */
export interface QuizProgressSaved {
  quiz: string;
  is_daily: boolean;
}

/**
 * The shape of a `QuizResultAck` response.
 */
export interface QuizResultAck {
  recorded: boolean;
}

/**
 * A player's totals for one character in one quiz.
 */
export interface QuizStatsRow {
  quiz: string;
  character_id: number;
  character_name: string;
  icon_name: string | null;
  wins: number;
  losses: number;
  attempts: number;
}

/**
 * A voice over drawn at random, with the character it belongs to.
 *
 * Only lines with both English audio and English text are drawn, and the
 * Travellers are left out - one character across twelve rows would meet
 * themselves.
 */
export interface QuizVoiceOverRound {
  id: number;
  type: string;
  title_english: string;
  text_english: string;
  audio_english: string;
  character_id: number;
  character_name: string;
  icon_name: string | null;
  wish_icon_name: string | null;
  rarity: number;
  element: string;
}
