// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * One page, as the admin form sees it - the row plus what it claims.
 */
export interface AdminSiteRoute {
  id: number;
  path: string;
  visibility: string;
  blocked: boolean;
  /** API paths this page claims. Empty means its data is not locked. */
  endpoints: string[];
  updated_at: string | null;
  updated_by: string | null;
}

/**
 * Every page, in the order the form draws them.
 */
export interface SiteRouteList {
  routes: AdminSiteRoute[];
  /** The visibility levels, most open first. */
  levels: string[];
}
