// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { SessionEntry } from './user.model';

/**
 * A session in the system-wide history, which is a session plus whose it is.
 *
 * Separate from SessionEntry rather than an extension of it because the two
 * answer different questions. A person reading their own list wants to know
 * which row is the browser they are sitting at; an admin reading every row
 * ever wants to know whose it is, and `current` would be false on all of them.
 */
export interface AdminSessionEntry {
  id: number;
  user_id: number;
  username: string;
  email: string;
  /** password, login_code, google, or email_link. */
  method: string;
  ip: string | null;
  user_agent: string | null;
  created_at: string;
  last_seen_at: string | null;
  expires_at: string;
  revoked_at: string | null;
  revoked_reason: string | null;
  /** Neither revoked nor expired, worked out against the server's clock. */
  active: boolean;
}

/**
 * The session history, and what a page of it was drawn from.
 */
export interface AdminSessionList {
  sessions: AdminSessionEntry[];
  /** Rows matching the filter, which is more than the page returns. */
  total: number;
  /** Live sessions across the whole installation, filter or no filter. */
  active: number;
  /** The methods present in the table, for the filter. */
  methods: string[];
}
