// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * One switch, as the admin form sees it.
 *
 * `type` is what makes the form generic: a new setting is a row in a migration
 * and two translation keys, not a new field on this class and a new control in
 * that template. `value` is text whatever the type says, because that is how
 * the column stores it - the form parses on the way in and the API validates
 * on the way back.
 */
export interface AdminSiteSetting {
  name: string;
  /** Which panel of the form it belongs under. */
  group_name: string;
  /** boolean, text, i18n, choice or routes. */
  type: string;
  /** For a 'choice', the values it may take. Empty otherwise. */
  options: string[];
  value: string | null;
  updated_at: string | null;
  /** Who threw the switch last, or null if nobody has since it was seeded. */
  updated_by: string | null;
}

/**
 * The shape of the site, before anybody has signed in.
 *
 * Open on purpose. A page cannot ask whether it should draw a maintenance
 * notice instead of itself after it has drawn itself, and it cannot ask who is
 * reading it before it knows whether reading is allowed. Nothing here is a
 * secret: it is what any visitor is about to see anyway.
 */
export interface PublicSiteSettings {
  /** Whether everything but the closed sign is switched off. */
  maintenance: boolean;
  /** The closed sign, one message per language. */
  maintenance_message: Record<string, string>;
  /** Whether anybody who is not an admin may start a session. */
  login_enabled: boolean;
  /** Whether the Google button is drawn and its tokens accepted. */
  google_login_enabled: boolean;
  /** Null when there is nothing to announce. */
  announcement: SiteAnnouncement | null;
  /** Sections of the site that are switched off - see the admin form. */
  disabled_routes: string[];
}

/**
 * A message across the top of every page, and how loudly it is saying it.
 */
export interface SiteAnnouncement {
  /** info, warning or danger - which decides the colour of the bar. */
  level: string;
  /** One message per language code. */
  message: Record<string, string>;
}

/**
 * Every switch, in the order the form draws them.
 */
export interface SiteSettingList {
  settings: AdminSiteSetting[];
}
