// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * A row of `languages` as the API reads it back.
 */
export interface Language {
  name: string;
  code: string;
  native_name: string;
  enabled: boolean;
  sort_order: number;
}

/**
 * A row of `translation_keys` as the API reads it back.
 */
export interface TranslationKey {
  name: string;
  description: string | null;
  site: string;
  created_at: string | null;
  updated_at: string | null;
}

/**
 * A body `User\TranslationKey` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface TranslationKeyPayload {
  name: string;
  description?: string | null;
  site?: string | null;
}
