// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

/**
 * What /api/users answers with.
 *
 * Every read here is `SELECT USER_COLUMNS`, which is the users table minus the
 * three columns that must never be published: the password hash, and the reset
 * token with its expiry.
 */
export interface AdminUser {
  id: number;
  role: string;
  username: string;
  email: string;
  email_confirmed: boolean;
  background: string | null;
  language: string;
  theme_main: string;
  theme_admin: string;
  /** Disabling an account sets this; nothing is destroyed. */
  deleted: boolean;
  version: string | null;
  created_at: string;
  updated_at: string | null;
}

/**
 * The shape of a `UserFilters` response.
 */
export interface UserFilters {
  roles: string[];
  byRole: Record<string, number>;
  disabled: number;
  total: number;
  /** How many admins are left, so the UI can explain a refused change. */
  admins: number;
  passwordMinLength: number;
}
