// Generated by angular/generate-api.mjs - do not edit.
// Source: php/generate-api-spec.php
// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs

import type { Saved } from '../types/common.type';

/**
 * A row of `weapons` as the API reads it back.
 */
export interface Weapon {
  id: number;
  name: string;
  type: string;
  rarity: number;
  icon_name: string | null;
  icon: string;
  icon_2_name: string | null;
  icon_2: string | null;
  icon_ascension: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  how_to_obtain: string | null;
  release_date: string | null;
  /** Raw JSON - PDO hands `JSONB` back as a string, undecoded. */
  effects: string | null;
  primary_stat: string | null;
  secondary_stat: string | null;
  version: string | null;
  description: string | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
  icon_ascension_name: string | null;
}

/**
 * A row of `weapons_ascensions` as the API reads it back.
 */
export interface WeaponAscension {
  id: number;
  weapon_id: number;
  phase: number;
  primary_stat_value: number;
  secondary_stat_value: number;
  start_level_from: number | null;
  start_level_to: number | null;
  end_level_from: number | null;
  end_level_to: number | null;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `weapons_ascensions_cost` as the API reads it back.
 */
export interface WeaponAscensionCost {
  id: number;
  weapon_ascension_id: number;
  material_id: number;
  quantity: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A row of `weapons_refinements` as the API reads it back.
 */
export interface WeaponRefinement {
  id: number;
  weapon_id: number;
  material_id: number;
  description: string | null;
  quantity: number;
  deleted: boolean;
  created_at: string | null;
  created_by: number;
  updated_at: string | null;
  updated_by: number | null;
}

/**
 * A body `Weapon` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface WeaponPayload {
  name: string;
  type: string;
  rarity: number;
  icon_name?: string | null;
  icon: string;
  icon_2_name?: string | null;
  icon_2?: string | null;
  icon_ascension?: string | null;
  primary_stat?: string | null;
  secondary_stat?: string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  how_to_obtain?: string[] | string | null;
  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */
  effects?: string[] | string | null;
  release_date?: string | null;
  version?: string | null;
  description?: string | null;
  icon_ascension_name?: string | null;
}

/**
 * A body `WeaponAscension` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface WeaponAscensionPayload {
  weapon_id: number;
  phase: number;
  primary_stat_value: number;
  secondary_stat_value: number;
  start_level_from?: number | null;
  start_level_to?: number | null;
  end_level_from?: number | null;
  end_level_to?: number | null;
}

/**
 * A body `WeaponAscensionCost` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface WeaponAscensionCostPayload {
  weapon_ascension_id: number;
  material_id: number;
  quantity: number;
}

/**
 * A body `WeaponRefinement` accepts, as validateBody() checks it.
 *
 * Optional here means what validateBody() means by it: a field is required
 * only when the model neither allows null nor supplies a default. Every
 * field is optional on an update, which is sent partial.
 */
export interface WeaponRefinementPayload {
  weapon_id: number;
  material_id: number;
  description: string;
  quantity: number;
}

/**
 * One ascension phase, with the materials it costs.
 *
 * registerFullResource() merges a child's own children in beside its columns
 * rather than nesting them under a key, so this is a WeaponAscension with one
 * more field - which is what `@merges` says.
 */
export type WeaponAscensionFull = Saved<WeaponAscensionPayload> & {
  costs: Saved<WeaponAscensionCostPayload>[];
};

/**
 * The shape of a `WeaponFull` response.
 */
export interface WeaponFull {
  weapon: Saved<WeaponPayload>;
  refinements: Saved<WeaponRefinementPayload>[];
  ascensions: WeaponAscensionFull[];
}

/**
 * The shape of a `WeaponFullRow` response.
 */
export type WeaponFullRow = Weapon & {
  refinements: Saved<WeaponRefinementPayload>[];
  ascensions: WeaponAscensionFull[];
};
