#!/usr/bin/env node
/**
 * generate-api.mjs - turns api-spec.json into src/app/api.
 *
 *   php ../php/generate-api-spec.php     # read the backend
 *   node generate-api.mjs                # write the client
 *
 * The output is shaped the way openapi-generator shapes a client: interfaces
 * for what crosses the wire, and one injectable service per resource with one
 * method per endpoint. Components ask a service; nothing outside src/app/api
 * touches HttpClient.
 *
 * Three kinds of interface come out of the backend, and keeping them apart is
 * the whole point - conflating them is how `id` ends up optional everywhere:
 *
 *   Character         a row as it is read, from the schema: id, created_at,
 *                     created_by, and every column declared
 *   CharacterPayload  a body as it is written, from the model's constructor,
 *                     which is exactly what validateBody() will accept
 *   CharacterFull     a response that is neither, from the ResponseShape class
 *                     beside the handler that returns it
 *
 * Nothing about a response is written by hand on this side any more. What is
 * left in src/app/api/types is the type-level plumbing - `Expanded`, `Saved` -
 * and the request and query shapes, which no endpoint declares because several
 * of them check their own bodies rather than going through validateRequest().
 *
 * Which service a route joins and what its method is called are decisions
 * rather than facts, so they live in api-config.mjs - which generate-openapi.mjs
 * reads too, so the client and the document describe the same API in the same
 * words.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  analyse,
  argType,
  BLOBS,
  camel,
  GROUP_DOCS,
  pascal,
  phpToTs,
  QUERIES,
  RESPONSES,
  sqlToTs,
} from './api-config.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SPEC = path.join(HERE, 'api-spec.json');
const OUT = path.join(HERE, 'src/app/api');

const spec = JSON.parse(fs.readFileSync(SPEC, 'utf8'));
const {
  routes,
  skipped,
  groupOf,
  tableOf,
  operationName,
  responseType,
  bodyType,
  payloadName,
  resolveModel,
  shapeByName,
  namedType,
  docType,
} = analyse(spec);

// ─────────────────────────────────────────────────────────────────────────────
// Emit
// ─────────────────────────────────────────────────────────────────────────────

const HEADER = (source) =>
  [
    '// Generated by angular/generate-api.mjs - do not edit.',
    `// Source: ${source}`,
    '// Regenerate: php ../php/generate-api-spec.php && node generate-api.mjs',
    '',
  ].join('\n');

/** Interfaces belong to the service that uses them most. */
const groupOfTable = new Map();
for (const route of routes) {
  const table = tableOf(route);
  if (table && !groupOfTable.has(table.table)) groupOfTable.set(table.table, groupOf(route));
}

/**
 * A payload model follows whichever table's routes validate against it.
 *
 * resolveModel() is what turns the name in the source back into the declared
 * class: a route may say `Role::class` under a `use`, or write
 * `User\Language::class` out in full.
 */
const groupOfModel = new Map();
for (const route of routes) {
  const model = route.payload && resolveModel(route.payload);
  if (model && !groupOfModel.has(model.name)) groupOfModel.set(model.name, groupOf(route));
}

function emitRowInterface(table) {
  const lines = [];
  lines.push('/**');
  lines.push(` * A row of \`${table.table}\` as the API reads it back.`);
  lines.push(' */');
  lines.push(`export interface ${table.interface} {`);

  for (const column of table.columns) {
    const type = sqlToTs(column);
    if (/^(JSON|JSONB)/i.test(column.sqlType)) {
      lines.push(`  /** Raw JSON - PDO hands \`${column.sqlType}\` back as a string, undecoded. */`);
    }
    lines.push(`  ${column.name}: ${column.nullable ? `${type} | null` : type};`);
  }

  lines.push('}');
  return lines.join('\n');
}

function emitPayloadInterface(model) {
  const jsonFields = new Set(model.jsonFields);
  const lines = [];
  lines.push('/**');
  lines.push(` * A body \`${model.name}\` accepts, as validateBody() checks it.`);
  lines.push(' *');
  lines.push(' * Optional here means what validateBody() means by it: a field is required');
  lines.push(' * only when the model neither allows null nor supplies a default. Every');
  lines.push(' * field is optional on an update, which is sent partial.');
  lines.push(' */');
  lines.push(`export interface ${payloadName(model.name)} {`);

  for (const field of model.fields) {
    if (jsonFields.has(field.name)) {
      lines.push(`  /** JSON: send the value; it reads back as a JSON string. See parseJsonColumn. */`);
    }
    // validateBody() calls a field required only when it neither allows null
    // nor has a default, so a nullable column may simply be left out.
    const optional = field.optional || field.nullable;
    lines.push(`  ${field.name}${optional ? '?' : ''}: ${phpToTs(field, jsonFields.has(field.name))};`);
  }

  lines.push('}');
  return lines.join('\n');
}

/**
 * A response shape, as the PHP class declares it.
 *
 * `@merges X` means the fields arrive alongside X's rather than nested under a
 * key, which is what registerFullResource() does with a child's own children -
 * so it comes out as an intersection rather than an interface of its own.
 */
function emitShapeInterface(shape) {
  const lines = [];

  const description = shape.description ?? `The shape of a \`${shape.name}\` response.`;

  lines.push('/**');
  for (const line of description.split('\n')) {
    lines.push(line ? ` * ${line}` : ' *');
  }
  lines.push(' */');

  const merged = shape.merges ? namedType(shape.merges) : null;
  lines.push(merged ? `export type ${shape.name} = ${merged} & {` : `export interface ${shape.name} {`);

  for (const field of shape.fields) {
    if (field.description) {
      lines.push(`  /** ${field.description.replace(/\n/g, ' ')} */`);
    }
    // A response is not a request: nullable here means the key is present and
    // holds null, not that it may be left out. Only a default makes it optional.
    const type = field.of ? docType(field.of) : phpToTs(field, false);
    const nullable = field.nullable && !type.endsWith('null') ? ' | null' : '';
    lines.push(`  ${field.name}${field.optional ? '?' : ''}: ${type}${nullable};`);
  }

  lines.push(merged ? '};' : '}');
  return lines.join('\n');
}

// ── models/<group>.model.ts ───────────────────────────────────────────────────

const modelFiles = new Map();
const exportedTypes = new Map();

const addTo = (group, text) => {
  if (!modelFiles.has(group)) modelFiles.set(group, []);
  modelFiles.get(group).push(text);
};

for (const table of spec.tables) {
  const group = groupOfTable.get(table.table);
  if (!group || !table.interface) continue;
  addTo(group, emitRowInterface(table));
  exportedTypes.set(table.interface, group);
}

for (const model of spec.models) {
  const group = groupOfModel.get(model.name);
  if (!group) continue;
  const name = payloadName(model.name);
  if (exportedTypes.has(name)) continue;
  addTo(group, emitPayloadInterface(model));
  exportedTypes.set(name, group);
}

/**
 * A response shape joins the service that answers with it.
 *
 * Most are named by a route. The rest are named by another shape - a
 * BackupDatabase only exists inside a BackupEntry - so those follow whichever
 * shape refers to them, resolved until nothing moves.
 */
const groupOfShape = new Map();
for (const route of routes) {
  const name = route.responds?.shape;
  if (name && shapeByName.has(name) && !groupOfShape.has(name)) groupOfShape.set(name, groupOf(route));
}

for (let settled = false; !settled; ) {
  settled = true;
  for (const shape of spec.shapes) {
    const group = groupOfShape.get(shape.name);
    if (!group) continue;

    // `of` is the element type of an array property; `types` covers a property
    // that holds one shape directly. Both have to travel with the shape that
    // names them, or the emitted file references a type it never imported.
    const referencedTypes = shape.fields.flatMap((field) => [field.of, ...field.types]);

    for (const referenced of [shape.merges, ...referencedTypes]) {
      const base = referenced?.replace(/\|null$/, '').replace(/\[\]$/, '');
      if (base && shapeByName.has(base) && !groupOfShape.has(base)) {
        groupOfShape.set(base, group);
        settled = false;
      }
    }
  }
}

for (const shape of spec.shapes) {
  const group = groupOfShape.get(shape.name);
  if (!group || exportedTypes.has(shape.name)) continue;
  addTo(group, emitShapeInterface(shape));
  exportedTypes.set(shape.name, group);
}

fs.mkdirSync(path.join(OUT, 'models'), { recursive: true });
fs.mkdirSync(path.join(OUT, 'services'), { recursive: true });

/**
 * The type-level helpers a model file leans on.
 *
 * Imported from the file that declares them rather than through the barrel: the
 * barrel reaches back into models, and a leaf import keeps that out of a cycle.
 */
const HELPERS = ['Expanded', 'Saved', 'UserStamp'];

for (const [group, blocks] of modelFiles) {
  const text = blocks.join('\n\n');
  const used = HELPERS.filter((helper) => new RegExp(`\\b${helper}<`).test(text));

  // A shape can name a type belonging to another service - a FeedbackPage holds
  // Feedback rows - so each file imports whatever it does not declare itself.
  const declared = new Set([...text.matchAll(/^export (?:interface|type) (\w+)/gm)].map((hit) => hit[1]));
  const byFile = new Map();

  for (const name of new Set([...text.matchAll(/\b([A-Z]\w+)\b/g)].map((hit) => hit[1]))) {
    const from = exportedTypes.get(name);
    if (!from || from === group || declared.has(name)) continue;
    if (!byFile.has(from)) byFile.set(from, []);
    byFile.get(from).push(name);
  }

  const borrowed = [...byFile]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([from, names]) => `import type { ${names.sort().join(', ')} } from './${from}.model';`);

  const body = [
    HEADER('php/generate-api-spec.php'),
    ...(used.length ? [`import type { ${used.join(', ')} } from '../types/common.type';`] : []),
    ...borrowed,
    ...(used.length || borrowed.length ? [''] : []),
    text,
    '',
  ].join('\n');

  fs.writeFileSync(path.join(OUT, 'models', `${group}.model.ts`), body.replace(/\n/g, '\r\n'));
}

const modelIndex = [
  HEADER('php/generate-api-spec.php'),
  [...modelFiles.keys()]
    .sort()
    .map((group) => `export * from './${group}.model';`)
    .join('\n'),
  '',
].join('\n');
fs.writeFileSync(path.join(OUT, 'models', 'index.ts'), modelIndex.replace(/\n/g, '\r\n'));

// ── services/<group>.service.ts ───────────────────────────────────────────────

/** One import, broken over several lines once it would run long. */
function importLine(names, from) {
  const single = `import { ${names.join(', ')} } from '${from}';`;
  if (single.length <= 120) return single;
  const wrapped = names.map((name) => `  ${name},`).join('\n');
  return `import {\n${wrapped}\n} from '${from}';`;
}

/**
 * The URL as a template literal, with `${id}` where the pattern had `{id}`.
 *
 * Anything but a numeric id is encoded on the way in. Several of these are
 * keyed by a name rather than a number, and the names are real text: a
 * character role is `Healer / Support`, and dropping that into a path unencoded
 * makes it two segments and a 404.
 */
const urlLiteral = (route) => {
  const byName = new Map(route.args.map((arg) => [arg.name, arg]));
  const url = route.path.replace(/\{(\w+)\}/g, (_, name) => {
    const value = camel(name);
    return '${' + (argType(byName.get(name)) === 'number' ? value : `encodeURIComponent(${value})`) + '}';
  });
  return url.includes('${') ? `\`${url}\`` : `'${route.path}'`;
};

const serviceFiles = new Map();
for (const route of routes) {
  const group = groupOf(route);
  if (!serviceFiles.has(group)) serviceFiles.set(group, []);
  serviceFiles.get(group).push(route);
}

const usedNames = new Map();
for (const [group, groupRoutes] of serviceFiles) {
  for (const route of groupRoutes) {
    const name = operationName(route);
    const key = `${group}.${name}`;
    if (!usedNames.has(key)) usedNames.set(key, []);
    usedNames.get(key).push(`${route.method} ${route.path}`);
  }
}

const collisions = [...usedNames].filter(([, paths]) => paths.length > 1);

function emitMethod(route) {
  const key = `${route.method} ${route.path}`;
  const name = operationName(route);
  const response = responseType(route);
  const body = bodyType(route);
  const query = QUERIES[key];

  const optionalQuery = query?.endsWith('?');
  const queryType = optionalQuery ? query.slice(0, -1) : query;

  const params = route.args.map((arg) => `${camel(arg.name)}: ${argType(arg)}`);
  if (body) params.push(`body: ${body}`);
  if (queryType) params.push(`params${optionalQuery ? '?' : ''}: ${queryType}`);
  else if (route.method === 'GET' && !route.args.length && !RESPONSES[key]) {
    // nothing: a plain collection read
  }

  const lines = [];
  lines.push('  /**');
  lines.push(`   * \`${route.method} ${route.path}\``);
  if (route.roles.length) {
    lines.push(`   *`);
    lines.push(`   * Requires the ${route.roles.map((role) => `\`${role}\``).join(' or ')} role.`);
  } else if (route.auth) {
    lines.push(`   *`);
    lines.push(`   * Requires a signed-in user.`);
  }
  lines.push('   */');

  const options = [];
  if (query) options.push('params: toHttpParams(params)');
  if (BLOBS.has(key)) options.push("responseType: 'blob' as 'json'");
  const optionsArg = options.length ? `, { ${options.join(', ')} }` : '';

  const url = urlLiteral(route);
  const verb = route.method.toLowerCase();
  const call =
    route.method === 'GET' || route.method === 'DELETE'
      ? `this._http.${verb}<${response}>(${url}${optionsArg})`
      : `this._http.${verb}<${response}>(${url}, body${optionsArg})`;

  lines.push(`  ${name}(${params.join(', ')}): Observable<${response}> {`);
  lines.push(`    return ${call};`);
  lines.push('  }');

  return lines.join('\n');
}

for (const [group, groupRoutes] of serviceFiles) {
  const sorted = [...groupRoutes].sort((a, b) => operationName(a).localeCompare(operationName(b)));

  const needed = new Set();
  for (const route of sorted) {
    for (const type of [responseType(route), bodyType(route), QUERIES[`${route.method} ${route.path}`]?.replace(/\?$/, '')]) {
      if (!type) continue;
      for (const word of type.match(/[A-Z][A-Za-z0-9]*/g) ?? []) needed.add(word);
    }
  }
  needed.delete('FormData');
  needed.delete('Partial');
  needed.delete('Record');
  needed.delete('Blob');

  const fromModels = [...needed].filter((type) => exportedTypes.has(type)).sort();
  const fromTypes = [...needed].filter((type) => !exportedTypes.has(type)).sort();

  const imports = [
    "import { Injectable, inject } from '@angular/core';",
    "import { HttpClient } from '@angular/common/http';",
    "import { Observable } from 'rxjs';",
  ];
  if (fromModels.length) imports.push(importLine(fromModels, '../models'));
  if (fromTypes.length) imports.push(importLine(fromTypes, '../types'));
  if (sorted.some((route) => QUERIES[`${route.method} ${route.path}`])) {
    imports.push("import { toHttpParams } from '../http-params';");
  }

  const className = `${pascal(group)}ApiService`;
  const body = [
    HEADER('php/generate-api-spec.php'),
    imports.join('\n'),
    '',
    '/**',
    ` * ${GROUP_DOCS[group] ?? `The \`${group}\` endpoints.`}`,
    ' */',
    "@Injectable({ providedIn: 'root' })",
    `export class ${className} {`,
    '  private readonly _http = inject(HttpClient);',
    '',
    sorted.map(emitMethod).join('\n\n'),
    '}',
    '',
  ].join('\n');

  fs.writeFileSync(path.join(OUT, 'services', `${group}.service.ts`), body.replace(/\n/g, '\r\n'));
}

const serviceIndex = [
  HEADER('php/generate-api-spec.php'),
  [...serviceFiles.keys()]
    .sort()
    .map((group) => `export * from './${group}.service';`)
    .join('\n'),
  '',
].join('\n');
fs.writeFileSync(path.join(OUT, 'services', 'index.ts'), serviceIndex.replace(/\n/g, '\r\n'));

// ── index.ts ──────────────────────────────────────────────────────────────────

const barrel = [
  HEADER('php/generate-api-spec.php'),
  "export * from './models';",
  "export * from './services';",
  "export * from './types';",
  "export * from './http-params';",
  "export * from './json-columns';",
  "export * from './form-data';",
  '',
].join('\n');
fs.writeFileSync(path.join(OUT, 'index.ts'), barrel.replace(/\n/g, '\r\n'));

// ── Report ────────────────────────────────────────────────────────────────────

const methodCount = routes.length;
console.log(`src/app/api`);
console.log(`  ${modelFiles.size} model files, ${exportedTypes.size} interfaces`);
console.log(`  ${serviceFiles.size} services, ${methodCount} methods`);
if (skipped) console.log(`  ${skipped} routes skipped (see SKIP_PREFIXES)`);

if (collisions.length) {
  console.log('\nname collisions - add an entry to NAMES:');
  for (const [key, paths] of collisions) console.log(`  ${key}\n    ${paths.join('\n    ')}`);
  process.exitCode = 1;
}

const untyped = routes.filter((route) => responseType(route) === 'unknown');
if (untyped.length) {
  console.log(`\n${untyped.length} endpoints answer with an unknown shape - add an entry to RESPONSES:`);
  for (const route of untyped) console.log(`  ${route.method} ${route.path}`);
}
