Listen 8000

<VirtualHost *:8000>
    DocumentRoot "f:/Repositories/anotoki-genshin-impact/php/api"
    <Directory "f:/Repositories/anotoki-genshin-impact/php/api">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

